// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelDreams.MsFacturacion.DataAccess.Context;

#nullable disable

namespace TravelDreams.MsFacturacion.DataAccess.Migrations
{
    [DbContext(typeof(FacturacionDbContext))]
    partial class FacturacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", b =>
                {
                    b.Property<int>("dfac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("dfac_id"));

                    b.Property<Guid>("cli_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("dfac_apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dfac_correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("dfac_direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("dfac_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("dfac_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dfac_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("dfac_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("dfac_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("dfac_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("dfac_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("dfac_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("dfac_nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dfac_numero_identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("dfac_razon_social")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("dfac_row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("dfac_telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("dfac_tipo_identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("dfac_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dfac_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dfac_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("dfac_id");

                    b.HasIndex("cli_guid");

                    b.HasIndex("dfac_guid")
                        .IsUnique();

                    b.ToTable("datos_facturacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_datos_facturacion_estado", "dfac_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_datos_facturacion_tipo_id", "dfac_tipo_identificacion IN ('CC','RUC','PASAPORTE','CEDULA','OTRO')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Property<int>("fac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("fac_id"));

                    b.Property<Guid>("cli_guid")
                        .HasColumnType("uuid");

                    b.Property<int?>("dfac_id")
                        .HasColumnType("integer");

                    b.Property<string>("fac_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("fac_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fac_fecha_emision_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("fac_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("fac_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("fac_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("fac_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("fac_numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("fac_observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("fac_row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<decimal>("fac_subtotal")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("fac_total")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("fac_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("fac_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("fac_valor_iva")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("pag_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("rev_guid")
                        .HasColumnType("uuid");

                    b.HasKey("fac_id");

                    b.HasIndex("cli_guid");

                    b.HasIndex("dfac_id");

                    b.HasIndex("fac_guid")
                        .IsUnique();

                    b.HasIndex("fac_numero")
                        .IsUnique();

                    b.HasIndex("pag_id")
                        .IsUnique();

                    b.HasIndex("rev_guid")
                        .IsUnique();

                    b.ToTable("facturas", null, t =>
                        {
                            t.HasCheckConstraint("ck_facturas_estado", "fac_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_facturas_iva", "fac_valor_iva >= 0");

                            t.HasCheckConstraint("ck_facturas_subtotal", "fac_subtotal >= 0");

                            t.HasCheckConstraint("ck_facturas_total", "fac_total >= 0");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.PagoEntity", b =>
                {
                    b.Property<int>("pag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pag_id"));

                    b.Property<Guid>("cli_guid")
                        .HasColumnType("uuid");

                    b.Property<int?>("dfac_id")
                        .HasColumnType("integer");

                    b.Property<string>("pag_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("APROBADO");

                    b.Property<DateTime>("pag_fecha_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("pag_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("pag_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("pag_metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("pag_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<decimal>("pag_monto")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("pag_observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("pag_origen_canal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("pag_referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("pag_row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("pag_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("rev_guid")
                        .HasColumnType("uuid");

                    b.HasKey("pag_id");

                    b.HasIndex("cli_guid");

                    b.HasIndex("dfac_id");

                    b.HasIndex("pag_guid")
                        .IsUnique();

                    b.HasIndex("pag_referencia")
                        .IsUnique();

                    b.HasIndex("rev_guid");

                    b.ToTable("pagos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pagos_estado", "pag_estado IN ('PENDIENTE','APROBADO','RECHAZADO')");

                            t.HasCheckConstraint("ck_pagos_monto", "pag_monto >= 0");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.V3.MarketplacePagoSolicitudV3Entity", b =>
                {
                    b.Property<long>("fsol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("fsol_id"));

                    b.Property<Guid>("cli_guid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fac_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("fac_numero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("fsol_correlation_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("fsol_created_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("fsol_error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("fsol_estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("fsol_payload_json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("fsol_updated_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rev_guid")
                        .HasColumnType("uuid");

                    b.HasKey("fsol_id");

                    b.HasIndex("cli_guid");

                    b.HasIndex("fsol_correlation_id")
                        .IsUnique();

                    b.HasIndex("fsol_estado");

                    b.HasIndex("rev_guid");

                    b.ToTable("facturacion_solicitudes_v3", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.HasOne("TravelDreams.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", "DatosFacturacion")
                        .WithMany("Facturas")
                        .HasForeignKey("dfac_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelDreams.MsFacturacion.DataAccess.Entities.PagoEntity", "Pago")
                        .WithOne("Factura")
                        .HasForeignKey("TravelDreams.MsFacturacion.DataAccess.Entities.FacturaEntity", "pag_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatosFacturacion");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.PagoEntity", b =>
                {
                    b.HasOne("TravelDreams.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", "DatosFacturacion")
                        .WithMany("Pagos")
                        .HasForeignKey("dfac_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatosFacturacion");
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("TravelDreams.MsFacturacion.DataAccess.Entities.PagoEntity", b =>
                {
                    b.Navigation("Factura");
                });
#pragma warning restore 612, 618
        }
    }
}
