CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE auditoria_log (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    log_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    log_servicio character varying(100) NOT NULL,
    log_tabla character varying(100) NOT NULL,
    log_operacion character varying(20) NOT NULL,
    log_registro_id integer,
    log_registro_guid uuid,
    log_datos_anteriores text,
    log_datos_nuevos text,
    log_fecha_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    log_usuario character varying(100) NOT NULL,
    log_ip character varying(45) NOT NULL,
    log_origen_canal character varying(200),
    log_correlation_id character varying(100),
    evento_id uuid,
    CONSTRAINT "PK_auditoria_log" PRIMARY KEY (log_id),
    CONSTRAINT ck_auditoria_log_delete CHECK (log_operacion <> 'DELETE' OR log_datos_nuevos IS NULL),
    CONSTRAINT ck_auditoria_log_insert CHECK (log_operacion <> 'INSERT' OR log_datos_anteriores IS NULL),
    CONSTRAINT ck_auditoria_log_operacion CHECK (log_operacion IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','BUSINESS_EVENT'))
);

CREATE TABLE eventos_procesados (
    ep_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ep_evento_id uuid NOT NULL,
    ep_tipo character varying(200) NOT NULL,
    ep_origen_servicio character varying(100) NOT NULL,
    ep_fecha_procesado_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ep_correlation_id character varying(100),
    CONSTRAINT "PK_eventos_procesados" PRIMARY KEY (ep_id)
);

CREATE UNIQUE INDEX "IX_auditoria_log_evento_id" ON auditoria_log (evento_id);

CREATE INDEX "IX_auditoria_log_log_correlation_id" ON auditoria_log (log_correlation_id);

CREATE INDEX "IX_auditoria_log_log_fecha_utc" ON auditoria_log (log_fecha_utc);

CREATE UNIQUE INDEX "IX_auditoria_log_log_guid" ON auditoria_log (log_guid);

CREATE INDEX "IX_auditoria_log_log_servicio_log_tabla_log_registro_id" ON auditoria_log (log_servicio, log_tabla, log_registro_id);

CREATE INDEX "IX_auditoria_log_log_usuario" ON auditoria_log (log_usuario);

CREATE UNIQUE INDEX "IX_eventos_procesados_ep_evento_id" ON eventos_procesados (ep_evento_id);

CREATE INDEX "IX_eventos_procesados_ep_origen_servicio" ON eventos_procesados (ep_origen_servicio);

CREATE INDEX "IX_eventos_procesados_ep_tipo" ON eventos_procesados (ep_tipo);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515014204_InitialAuditoriaSchema', '10.0.4');

COMMIT;

