// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelDreams.MsAuditoria.DataAccess.Context;

#nullable disable

namespace TravelDreams.MsAuditoria.DataAccess.Migrations
{
    [DbContext(typeof(AuditoriaDbContext))]
    partial class AuditoriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDreams.MsAuditoria.DataAccess.Entities.AuditoriaLogEntity", b =>
                {
                    b.Property<long>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("log_id"));

                    b.Property<Guid?>("evento_id")
                        .HasColumnType("uuid");

                    b.Property<string>("log_correlation_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("log_datos_anteriores")
                        .HasColumnType("text");

                    b.Property<string>("log_datos_nuevos")
                        .HasColumnType("text");

                    b.Property<DateTime>("log_fecha_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("log_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("log_ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("log_operacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("log_origen_canal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("log_registro_guid")
                        .HasColumnType("uuid");

                    b.Property<int?>("log_registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("log_servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("log_tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("log_usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("log_id");

                    b.HasIndex("evento_id")
                        .IsUnique();

                    b.HasIndex("log_correlation_id");

                    b.HasIndex("log_fecha_utc");

                    b.HasIndex("log_guid")
                        .IsUnique();

                    b.HasIndex("log_usuario");

                    b.HasIndex("log_servicio", "log_tabla", "log_registro_id");

                    b.ToTable("auditoria_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_auditoria_log_delete", "log_operacion <> 'DELETE' OR log_datos_nuevos IS NULL");

                            t.HasCheckConstraint("ck_auditoria_log_insert", "log_operacion <> 'INSERT' OR log_datos_anteriores IS NULL");

                            t.HasCheckConstraint("ck_auditoria_log_operacion", "log_operacion IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','BUSINESS_EVENT')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAuditoria.DataAccess.Entities.EventoProcesadoEntity", b =>
                {
                    b.Property<long>("ep_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ep_id"));

                    b.Property<string>("ep_correlation_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ep_evento_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ep_fecha_procesado_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ep_origen_servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ep_tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ep_id");

                    b.HasIndex("ep_evento_id")
                        .IsUnique();

                    b.HasIndex("ep_origen_servicio");

                    b.HasIndex("ep_tipo");

                    b.ToTable("eventos_procesados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
