// <auto-generated />
using AtraccionesTuristicas.Backend.LA.DataAccess.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AtraccionesTuristicas.Backend.LA.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    [Migration("20260509034500_AddSecurityAuditTriggers")]
    public partial class AddSecurityAuditTriggers
    {
    }
}
