// <auto-generated />
using System;
using AtraccionesTuristicas.Backend.LA.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtraccionesTuristicas.Backend.LA.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    [Migration("20260506043534_AddDatabaseTriggers")]
    partial class AddDatabaseTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Auditoria.AuditoriaLogEntity", b =>
                {
                    b.Property<long>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("log_id"));

                    b.Property<string>("log_datos_anteriores")
                        .HasColumnType("text");

                    b.Property<string>("log_datos_nuevos")
                        .HasColumnType("text");

                    b.Property<DateTime>("log_fecha_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("log_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("log_ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("log_operacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("log_origen_canal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("log_registro_guid")
                        .HasColumnType("uuid");

                    b.Property<int?>("log_registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("log_tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("log_usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("log_id");

                    b.HasIndex("log_fecha_utc");

                    b.HasIndex("log_guid")
                        .IsUnique();

                    b.HasIndex("log_usuario");

                    b.HasIndex("log_tabla", "log_registro_id");

                    b.ToTable("auditoria_log", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", b =>
                {
                    b.Property<int>("at_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("at_id"));

                    b.Property<string>("at_descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("at_direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("at_disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("at_duracion_minutos")
                        .HasColumnType("integer");

                    b.Property<string>("at_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("at_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("at_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("at_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("at_free_cancellation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("at_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("at_incluye_acompaniante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("at_incluye_transporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("at_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("at_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("at_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("at_nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("at_num_establecimiento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("at_precio_referencia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("at_punto_encuentro")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("at_skip_the_line")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("at_total_resenias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("at_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("at_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("at_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("des_id")
                        .HasColumnType("integer");

                    b.HasKey("at_id");

                    b.HasIndex("at_guid")
                        .IsUnique();

                    b.HasIndex("at_nombre");

                    b.HasIndex("des_id");

                    b.ToTable("atraccion", null, t =>
                        {
                            t.HasCheckConstraint("ck_atraccion_duracion", "at_duracion_minutos IS NULL OR at_duracion_minutos > 0");

                            t.HasCheckConstraint("ck_atraccion_estado", "at_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_atraccion_precio", "at_precio_referencia IS NULL OR at_precio_referencia >= 0");

                            t.HasCheckConstraint("ck_atraccion_resenias", "at_total_resenias >= 0");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.CategoriaEntity", b =>
                {
                    b.Property<int>("cat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cat_id"));

                    b.Property<string>("cat_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("cat_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("cat_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("cat_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("cat_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("cat_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cat_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cat_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cat_nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("cat_parent_id")
                        .HasColumnType("integer");

                    b.Property<string>("cat_tagname")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("cat_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cat_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cat_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("cat_id");

                    b.HasIndex("cat_guid")
                        .IsUnique();

                    b.HasIndex("cat_parent_id");

                    b.HasIndex("cat_tagname");

                    b.ToTable("categoria", null, t =>
                        {
                            t.HasCheckConstraint("ck_categoria_estado", "cat_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_categoria_selfref", "cat_parent_id IS NULL OR cat_parent_id <> cat_id");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.DestinoEntity", b =>
                {
                    b.Property<int>("des_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("des_id"));

                    b.Property<string>("des_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("des_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("des_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("des_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("des_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("des_imagen_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("des_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("des_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("des_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("des_nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("des_pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("des_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("des_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("des_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("des_id");

                    b.HasIndex("des_guid")
                        .IsUnique();

                    b.HasIndex("des_pais");

                    b.ToTable("destino", null, t =>
                        {
                            t.HasCheckConstraint("ck_destino_estado", "des_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.IdiomaEntity", b =>
                {
                    b.Property<int>("id_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_id"));

                    b.Property<string>("id_codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("id_descripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("id_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("id_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("id_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("id_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("id_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("id_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("id_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("id_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("id_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("id_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("id_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_id");

                    b.HasIndex("id_codigo")
                        .IsUnique();

                    b.HasIndex("id_descripcion")
                        .IsUnique();

                    b.HasIndex("id_guid")
                        .IsUnique();

                    b.ToTable("idioma", null, t =>
                        {
                            t.HasCheckConstraint("ck_idioma_estado", "id_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.ImagenEntity", b =>
                {
                    b.Property<int>("img_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("img_id"));

                    b.Property<string>("img_descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("img_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("img_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("img_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("img_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("img_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("img_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("img_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("img_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("img_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("img_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("img_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("img_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("img_id");

                    b.HasIndex("img_guid")
                        .IsUnique();

                    b.ToTable("imagen", null, t =>
                        {
                            t.HasCheckConstraint("ck_imagen_estado", "img_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.IncluyeEntity", b =>
                {
                    b.Property<int>("inc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("inc_id"));

                    b.Property<string>("inc_descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("inc_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<Guid>("inc_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("inc_tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("INCLUYE");

                    b.HasKey("inc_id");

                    b.HasIndex("inc_guid")
                        .IsUnique();

                    b.ToTable("incluye", null, t =>
                        {
                            t.HasCheckConstraint("ck_incluye_estado", "inc_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_incluye_tipo", "inc_tipo IN ('INCLUYE','NO_INCLUYE','ETIQUETA')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.AtraccionIncluyeEntity", b =>
                {
                    b.Property<int>("inc_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<string>("ai_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ai_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ai_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ai_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ai_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("inc_id", "at_id");

                    b.HasIndex("at_id");

                    b.ToTable("atraccion_incluye", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.CategoriaAtraccionEntity", b =>
                {
                    b.Property<int>("cat_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<string>("ca_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ca_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ca_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ca_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ca_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("cat_id", "at_id");

                    b.HasIndex("at_id");

                    b.ToTable("categoria_atraccion", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.IdiomaAtraccionEntity", b =>
                {
                    b.Property<int>("id_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<string>("ia_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ia_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ia_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ia_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ia_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_id", "at_id");

                    b.HasIndex("at_id");

                    b.ToTable("idioma_atraccion", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.ImagenAtraccionEntity", b =>
                {
                    b.Property<int>("img_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<bool>("ima_es_principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ima_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ima_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ima_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ima_orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ima_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ima_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("img_id", "at_id");

                    b.HasIndex("at_id", "ima_es_principal");

                    b.ToTable("imagen_atraccion", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.ClienteEntity", b =>
                {
                    b.Property<int>("cli_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cli_id"));

                    b.Property<string>("cli_apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cli_correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("cli_direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("cli_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("cli_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("cli_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("cli_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("cli_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cli_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cli_nombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cli_numero_identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("cli_razon_social")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("cli_row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("cli_telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("cli_tipo_identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("cli_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cli_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("usu_id")
                        .HasColumnType("integer");

                    b.HasKey("cli_id");

                    b.HasIndex("cli_guid")
                        .IsUnique();

                    b.HasIndex("cli_numero_identificacion")
                        .IsUnique();

                    b.HasIndex("usu_id");

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_estado", "cli_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_clientes_tipo_id", "cli_tipo_identificacion IN ('CC','RUC','PASAPORTE','CEDULA','OTRO')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.DatosFacturacionEntity", b =>
                {
                    b.Property<int>("dfac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("dfac_id"));

                    b.Property<string>("dfac_apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dfac_correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("dfac_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("dfac_nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dfac_telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("fac_id")
                        .HasColumnType("integer");

                    b.HasKey("dfac_id");

                    b.HasIndex("dfac_guid")
                        .IsUnique();

                    b.HasIndex("fac_id")
                        .IsUnique();

                    b.ToTable("datos_facturacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_dfac_correo", "dfac_correo LIKE '%@%.%'");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.RolEntity", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rol_id"));

                    b.Property<string>("rol_descripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("rol_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("rol_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rol_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rol_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rol_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rol_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rol_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rol_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("rol_id");

                    b.HasIndex("rol_guid")
                        .IsUnique();

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_roles_estado", "rol_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.UsuarioEntity", b =>
                {
                    b.Property<int>("usu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usu_id"));

                    b.Property<string>("usu_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("usu_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("usu_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("usu_fecha_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("usu_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("usu_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("usu_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("usu_ip_registro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("usu_login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("usu_password_hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("usu_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("usu_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("usu_usuario_registro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("usu_id");

                    b.HasIndex("usu_guid")
                        .IsUnique();

                    b.HasIndex("usu_login")
                        .IsUnique();

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_estado", "usu_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.UsuarioRolEntity", b =>
                {
                    b.Property<int>("usu_rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usu_rol_id"));

                    b.Property<int>("rol_id")
                        .HasColumnType("integer");

                    b.Property<int>("usu_id")
                        .HasColumnType("integer");

                    b.Property<string>("usu_rol_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.HasKey("usu_rol_id");

                    b.HasIndex("rol_id");

                    b.HasIndex("usu_id", "rol_id")
                        .IsUnique();

                    b.ToTable("usuarioxroles", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarioxroles_estado", "usu_rol_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.FacturaEntity", b =>
                {
                    b.Property<int>("fac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("fac_id"));

                    b.Property<string>("fac_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("fac_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fac_fecha_emision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("fac_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("fac_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("fac_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("fac_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("fac_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("fac_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("fac_motivo_inhabilitacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("fac_numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("fac_observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("fac_origen_canal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("fac_row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<decimal>("fac_total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("fac_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("fac_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("fac_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("pag_id")
                        .HasColumnType("integer");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.HasKey("fac_id");

                    b.HasIndex("fac_guid")
                        .IsUnique();

                    b.HasIndex("fac_numero")
                        .IsUnique();

                    b.HasIndex("pag_id")
                        .IsUnique();

                    b.HasIndex("rev_id")
                        .IsUnique();

                    b.ToTable("facturas", null, t =>
                        {
                            t.HasCheckConstraint("ck_facturas_estado", "fac_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_facturas_total", "fac_total >= 0");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.HorarioEntity", b =>
                {
                    b.Property<int>("hor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("hor_id"));

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<int>("hor_cupos_disponibles")
                        .HasColumnType("integer");

                    b.Property<string>("hor_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateOnly>("hor_fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("hor_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("hor_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("hor_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("hor_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeOnly?>("hor_hora_fin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("hor_hora_inicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("hor_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("hor_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("hor_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("hor_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("hor_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("hor_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("hor_id");

                    b.HasIndex("hor_guid")
                        .IsUnique();

                    b.HasIndex("at_id", "hor_fecha", "hor_hora_inicio")
                        .IsUnique();

                    b.ToTable("horario", null, t =>
                        {
                            t.HasCheckConstraint("ck_horario_cupos", "hor_cupos_disponibles >= 0");

                            t.HasCheckConstraint("ck_horario_estado", "hor_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.PagoEntity", b =>
                {
                    b.Property<int>("pag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pag_id"));

                    b.Property<string>("pag_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime?>("pag_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("pag_fecha_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("pag_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("pag_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("pag_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("pag_metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("pag_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<decimal>("pag_monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("pag_origen_canal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("pag_referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("pag_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("pag_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.HasKey("pag_id");

                    b.HasIndex("pag_guid")
                        .IsUnique();

                    b.HasIndex("pag_referencia")
                        .IsUnique();

                    b.HasIndex("rev_id");

                    b.ToTable("pagos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pagos_estado", "pag_estado IN ('PENDIENTE','APROBADO','RECHAZADO')");

                            t.HasCheckConstraint("ck_pagos_monto", "pag_monto >= 0");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReseniaEntity", b =>
                {
                    b.Property<int>("rsn_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rsn_id"));

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.Property<string>("rsn_comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("rsn_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime>("rsn_fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("rsn_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("rsn_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("rsn_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rsn_ip_creacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rsn_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rsn_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<short>("rsn_rating")
                        .HasColumnType("smallint");

                    b.Property<string>("rsn_usuario_creacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rsn_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rsn_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("rsn_id");

                    b.HasIndex("at_id");

                    b.HasIndex("rev_id")
                        .IsUnique();

                    b.HasIndex("rsn_guid")
                        .IsUnique();

                    b.ToTable("resenia", null, t =>
                        {
                            t.HasCheckConstraint("ck_resenia_rating", "rsn_rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaDetalleEntity", b =>
                {
                    b.Property<int>("rdet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rdet_id"));

                    b.Property<int>("rdet_cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("rdet_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("rdet_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rdet_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rdet_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rdet_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rdet_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<decimal>("rdet_precio_unit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("rdet_subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("rdet_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rdet_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.Property<int>("tck_id")
                        .HasColumnType("integer");

                    b.HasKey("rdet_id");

                    b.HasIndex("rdet_guid")
                        .IsUnique();

                    b.HasIndex("tck_id");

                    b.HasIndex("rev_id", "tck_id")
                        .IsUnique();

                    b.ToTable("reserva_detalle", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", b =>
                {
                    b.Property<int>("rev_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rev_id"));

                    b.Property<int>("cli_id")
                        .HasColumnType("integer");

                    b.Property<int>("hor_id")
                        .HasColumnType("integer");

                    b.Property<string>("rev_codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("rev_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime?>("rev_fecha_cancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rev_fecha_expiracion_utc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("rev_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rev_fecha_reserva_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rev_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rev_ip_cancelacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rev_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rev_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rev_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("rev_motivo_cancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("rev_origen_canal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("rev_subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("rev_total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("rev_usuario_cancelacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rev_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rev_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("rev_valor_iva")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("rev_id");

                    b.HasIndex("cli_id");

                    b.HasIndex("hor_id");

                    b.HasIndex("rev_codigo")
                        .IsUnique();

                    b.HasIndex("rev_guid")
                        .IsUnique();

                    b.ToTable("reservas", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservas_estado", "rev_estado IN ('PENDIENTE','PAGADA','CONFIRMADA','CANCELADA','EXPIRADA','USADA','NO_SHOW')");

                            t.HasCheckConstraint("ck_reservas_iva", "rev_valor_iva >= 0");

                            t.HasCheckConstraint("ck_reservas_subtotal", "rev_subtotal >= 0");

                            t.HasCheckConstraint("ck_reservas_total", "rev_total >= 0");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEstadoHistorialEntity", b =>
                {
                    b.Property<int>("reh_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reh_id"));

                    b.Property<string>("reh_estado_anterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("reh_estado_nuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("reh_fecha_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("reh_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("reh_ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("reh_observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("reh_usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.HasKey("reh_id");

                    b.HasIndex("reh_guid")
                        .IsUnique();

                    b.HasIndex("rev_id");

                    b.ToTable("reserva_estado_historial", (string)null);
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.TicketEntity", b =>
                {
                    b.Property<int>("tck_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tck_id"));

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<int>("tck_capacidad_maxima")
                        .HasColumnType("integer");

                    b.Property<string>("tck_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("tck_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("tck_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("tck_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("tck_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("tck_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tck_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tck_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tck_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<decimal>("tck_precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("tck_tipo_participante")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Adulto");

                    b.Property<string>("tck_titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("tck_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tck_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tck_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("tck_id");

                    b.HasIndex("at_id");

                    b.HasIndex("tck_guid")
                        .IsUnique();

                    b.ToTable("ticket", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_capacidad", "tck_capacidad_maxima > 0");

                            t.HasCheckConstraint("ck_ticket_estado", "tck_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_ticket_precio", "tck_precio >= 0");
                        });
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.DestinoEntity", "Destino")
                        .WithMany("Atracciones")
                        .HasForeignKey("des_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.CategoriaEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.CategoriaEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("cat_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.AtraccionIncluyeEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("AtraccionIncluyes")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.IncluyeEntity", "Incluye")
                        .WithMany("AtraccionIncluyes")
                        .HasForeignKey("inc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Incluye");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.CategoriaAtraccionEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.CategoriaEntity", "Categoria")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.IdiomaAtraccionEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.IdiomaEntity", "Idioma")
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("id_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.CatalogoRelaciones.ImagenAtraccionEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("ImagenAtracciones")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.ImagenEntity", "Imagen")
                        .WithMany("ImagenAtracciones")
                        .HasForeignKey("img_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.ClienteEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.UsuarioEntity", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("usu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.DatosFacturacionEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.FacturaEntity", "Factura")
                        .WithOne("DatosFacturacion")
                        .HasForeignKey("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.DatosFacturacionEntity", "fac_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.UsuarioRolEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.RolEntity", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.UsuarioEntity", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("usu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.FacturaEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.PagoEntity", "Pago")
                        .WithOne()
                        .HasForeignKey("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.FacturaEntity", "pag_id");

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", "Reserva")
                        .WithOne("Factura")
                        .HasForeignKey("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.FacturaEntity", "rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.HorarioEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("Horarios")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.PagoEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReseniaEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("Resenias")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", "Reserva")
                        .WithOne("Resenia")
                        .HasForeignKey("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReseniaEntity", "rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaDetalleEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", "Reserva")
                        .WithMany("Detalles")
                        .HasForeignKey("rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.TicketEntity", "Ticket")
                        .WithMany("ReservaDetalles")
                        .HasForeignKey("tck_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.ClienteEntity", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("cli_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.HorarioEntity", "Horario")
                        .WithMany("Reservas")
                        .HasForeignKey("hor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEstadoHistorialEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", "Reserva")
                        .WithMany("EstadoHistorial")
                        .HasForeignKey("rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.TicketEntity", b =>
                {
                    b.HasOne("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("Tickets")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.AtraccionEntity", b =>
                {
                    b.Navigation("AtraccionIncluyes");

                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Horarios");

                    b.Navigation("IdiomaAtracciones");

                    b.Navigation("ImagenAtracciones");

                    b.Navigation("Resenias");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.CategoriaEntity", b =>
                {
                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.DestinoEntity", b =>
                {
                    b.Navigation("Atracciones");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.IdiomaEntity", b =>
                {
                    b.Navigation("IdiomaAtracciones");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.ImagenEntity", b =>
                {
                    b.Navigation("ImagenAtracciones");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Catalogo.IncluyeEntity", b =>
                {
                    b.Navigation("AtraccionIncluyes");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Cliente.ClienteEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.RolEntity", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Identity.UsuarioEntity", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.FacturaEntity", b =>
                {
                    b.Navigation("DatosFacturacion");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.HorarioEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.ReservaEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("EstadoHistorial");

                    b.Navigation("Factura");

                    b.Navigation("Pagos");

                    b.Navigation("Resenia");
                });

            modelBuilder.Entity("AtraccionesTuristicas.Backend.LA.DataAccess.Entities.Operacion.TicketEntity", b =>
                {
                    b.Navigation("ReservaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
