// <auto-generated />
using AtraccionesTuristicas.Backend.LA.DataAccess.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AtraccionesTuristicas.Backend.LA.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    [Migration("20260508184000_EnforceSinglePendingReservaPerAtraccion")]
    public partial class EnforceSinglePendingReservaPerAtraccion
    {
    }
}
