namespace AtraccionesTuristicas.Backend.LA.Business.Services.Operacion;

public sealed class HorarioService : IHorarioService
    {
        private readonly IHorarioDataService _data; public HorarioService(IHorarioDataService data) => _data = data;
        public async Task<IReadOnlyList<HorarioResponse>> ListarAsync(CurrentUserData user, CancellationToken cancellationToken = default) { Support.Guard.EnsureAdmin(user); return (await _data.ListarAsync(cancellationToken)).Select(Map.Horario).ToList(); }
        public async Task<HorarioResponse> ObtenerPorGuidAsync(Guid guid, CurrentUserData user, CancellationToken cancellationToken = default) { Support.Guard.EnsureAdmin(user); return Map.Horario(await _data.ObtenerPorGuidAsync(guid, cancellationToken) ?? throw new NotFoundException("Horario no encontrado.")); }
        public async Task<IReadOnlyList<HorarioDisponibleResponse>> ListarDisponiblesPorAtraccionAsync(HorarioFiltroRequest request, CancellationToken cancellationToken = default) => (await _data.ListarDisponiblesPorAtraccionAsync(request.AtraccionGuid, request.Fecha, cancellationToken)).Select(x => new HorarioDisponibleResponse { Id = x.Id, Guid = x.Guid, AtraccionId = x.AtraccionId, Fecha = x.Fecha, HoraInicio = x.HoraInicio, HoraFin = x.HoraFin, CuposDisponibles = x.CuposDisponibles, Estado = x.Estado }).ToList();
        public async Task<HorarioResponse> CrearAsync(CrearHorarioRequest request, CurrentUserData user, CancellationToken cancellationToken = default) { Support.Guard.EnsureAdmin(user); Validate(request); return Map.Horario(await _data.CrearAsync(ToDataModel(request), cancellationToken)); }
        public async Task<HorarioResponse> ActualizarAsync(ActualizarHorarioRequest request, CurrentUserData user, CancellationToken cancellationToken = default) { Support.Guard.EnsureAdmin(user); Validate(request); return Map.Horario(await _data.ActualizarAsync(ToDataModel(request), cancellationToken) ?? throw new NotFoundException("Horario no encontrado.")); }
        public async Task<HorarioResponse> CambiarEstadoAsync(CambiarEstadoHorarioRequest request, CurrentUserData user, CancellationToken cancellationToken = default) { Support.Guard.EnsureAdmin(user); return Map.Horario(await _data.CambiarEstadoAsync(request.Guid, request.Estado, request.Usuario, request.Ip, cancellationToken) ?? throw new NotFoundException("Horario no encontrado.")); }
        public Task<int> DesactivarPasadosOSinCuposAsync(CurrentUserData user, CancellationToken cancellationToken = default) { Support.Guard.EnsureAdmin(user); return _data.DesactivarPasadosOSinCuposAsync(user.Login, user.Ip, cancellationToken); }
        private static HorarioDataModel ToDataModel(CrearHorarioRequest request) => new() { AtraccionId = request.AtraccionId, Fecha = request.Fecha == default ? new DateOnly(2099, 12, 31) : request.Fecha, HoraInicio = request.HoraInicio, HoraFin = request.HoraFin, CuposDisponibles = request.CuposDisponibles, DiasSemana = string.IsNullOrWhiteSpace(request.DiasSemana) ? "0,1,2,3,4,5,6" : request.DiasSemana, UsuarioIngreso = request.UsuarioIngreso, IpIngreso = request.IpIngreso, Estado = BusinessConstants.EstadoActivo };
        private static HorarioDataModel ToDataModel(ActualizarHorarioRequest request) { var model = ToDataModel((CrearHorarioRequest)request); model.Guid = request.Guid; model.Estado = request.Estado; model.UsuarioModificacion = request.UsuarioModificacion; model.IpModificacion = request.IpModificacion; return model; }
        private static void Validate(CrearHorarioRequest request) { var errors = new List<string>(); Support.Guard.Positive(request.AtraccionId, "AtraccionId", errors); Support.Guard.Positive(request.CuposDisponibles, "CuposDisponibles", errors); if (request.Fecha != default && request.Fecha < DateOnly.FromDateTime(DateTime.UtcNow)) errors.Add("Fecha no puede ser pasada."); if (request.HoraFin is not null && request.HoraFin <= request.HoraInicio) errors.Add("HoraFin debe ser mayor a HoraInicio."); Support.Guard.ThrowIfAny(errors); }
    }

