// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelDreams.MsIdentidad.DataAccess.Context;

#nullable disable

namespace TravelDreams.MsIdentidad.DataAccess.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    partial class IdentidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDreams.MsIdentidad.DataAccess.Entities.RolEntity", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rol_id"));

                    b.Property<string>("rol_descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rol_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("rol_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rol_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rol_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rol_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rol_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rol_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rol_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("rol_id");

                    b.HasIndex("rol_descripcion")
                        .IsUnique();

                    b.HasIndex("rol_guid")
                        .IsUnique();

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_roles_estado", "rol_estado IN ('A','I')");
                        });

                    b.HasData(
                        new
                        {
                            rol_id = 1,
                            rol_descripcion = "ADMIN",
                            rol_estado = "A",
                            rol_fecha_ingreso = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            rol_guid = new Guid("11111111-1111-1111-1111-111111111111"),
                            rol_ip_ingreso = "migration",
                            rol_usuario_ingreso = "seed"
                        },
                        new
                        {
                            rol_id = 2,
                            rol_descripcion = "CLIENTE",
                            rol_estado = "A",
                            rol_fecha_ingreso = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            rol_guid = new Guid("22222222-2222-2222-2222-222222222222"),
                            rol_ip_ingreso = "migration",
                            rol_usuario_ingreso = "seed"
                        });
                });

            modelBuilder.Entity("TravelDreams.MsIdentidad.DataAccess.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("usu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usu_id"));

                    b.Property<string>("usu_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("usu_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("usu_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("usu_fecha_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("usu_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("usu_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("usu_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("usu_ip_registro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("usu_login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("usu_password_hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("usu_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("usu_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("usu_usuario_registro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("usu_id");

                    b.HasIndex("usu_guid")
                        .IsUnique();

                    b.HasIndex("usu_login")
                        .IsUnique();

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_estado", "usu_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsIdentidad.DataAccess.Entities.UsuarioRolEntity", b =>
                {
                    b.Property<int>("usu_rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usu_rol_id"));

                    b.Property<int>("rol_id")
                        .HasColumnType("integer");

                    b.Property<int>("usu_id")
                        .HasColumnType("integer");

                    b.Property<string>("usu_rol_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.HasKey("usu_rol_id");

                    b.HasIndex("rol_id");

                    b.HasIndex("usu_id", "rol_id")
                        .IsUnique();

                    b.ToTable("usuarioxroles", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarioxroles_estado", "usu_rol_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsIdentidad.DataAccess.Entities.UsuarioRolEntity", b =>
                {
                    b.HasOne("TravelDreams.MsIdentidad.DataAccess.Entities.RolEntity", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelDreams.MsIdentidad.DataAccess.Entities.UsuarioEntity", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("usu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TravelDreams.MsIdentidad.DataAccess.Entities.RolEntity", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("TravelDreams.MsIdentidad.DataAccess.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
