CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE roles (
    rol_id integer GENERATED BY DEFAULT AS IDENTITY,
    rol_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    rol_descripcion character varying(100) NOT NULL,
    rol_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    rol_usuario_ingreso character varying(100) NOT NULL,
    rol_ip_ingreso character varying(45) NOT NULL,
    rol_fecha_eliminacion timestamp with time zone,
    rol_usuario_eliminacion character varying(100),
    rol_ip_eliminacion character varying(45),
    rol_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_roles" PRIMARY KEY (rol_id),
    CONSTRAINT ck_roles_estado CHECK (rol_estado IN ('A','I'))
);

CREATE TABLE usuario (
    usu_id integer GENERATED BY DEFAULT AS IDENTITY,
    usu_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    usu_login character varying(150) NOT NULL,
    usu_password_hash character varying(500) NOT NULL,
    usu_fecha_registro timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    usu_usuario_registro character varying(100) NOT NULL,
    usu_ip_registro character varying(45) NOT NULL,
    usu_fecha_mod timestamp with time zone,
    usu_usuario_mod character varying(100),
    usu_ip_mod character varying(45),
    usu_fecha_eliminacion timestamp with time zone,
    usu_usuario_eliminacion character varying(100),
    usu_ip_eliminacion character varying(45),
    usu_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_usuario" PRIMARY KEY (usu_id),
    CONSTRAINT ck_usuario_estado CHECK (usu_estado IN ('A','I'))
);

CREATE TABLE usuarioxroles (
    usu_rol_id integer GENERATED BY DEFAULT AS IDENTITY,
    usu_id integer NOT NULL,
    rol_id integer NOT NULL,
    usu_rol_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_usuarioxroles" PRIMARY KEY (usu_rol_id),
    CONSTRAINT ck_usuarioxroles_estado CHECK (usu_rol_estado IN ('A','I')),
    CONSTRAINT "FK_usuarioxroles_roles_rol_id" FOREIGN KEY (rol_id) REFERENCES roles (rol_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_usuarioxroles_usuario_usu_id" FOREIGN KEY (usu_id) REFERENCES usuario (usu_id) ON DELETE CASCADE
);

INSERT INTO roles (rol_id, rol_descripcion, rol_estado, rol_fecha_eliminacion, rol_fecha_ingreso, rol_guid, rol_ip_eliminacion, rol_ip_ingreso, rol_usuario_eliminacion, rol_usuario_ingreso)
VALUES (1, 'ADMIN', 'A', NULL, TIMESTAMPTZ '2026-01-01T00:00:00Z', '11111111-1111-1111-1111-111111111111', NULL, 'migration', NULL, 'seed');
INSERT INTO roles (rol_id, rol_descripcion, rol_estado, rol_fecha_eliminacion, rol_fecha_ingreso, rol_guid, rol_ip_eliminacion, rol_ip_ingreso, rol_usuario_eliminacion, rol_usuario_ingreso)
VALUES (2, 'CLIENTE', 'A', NULL, TIMESTAMPTZ '2026-01-01T00:00:00Z', '22222222-2222-2222-2222-222222222222', NULL, 'migration', NULL, 'seed');

CREATE UNIQUE INDEX "IX_roles_rol_descripcion" ON roles (rol_descripcion);

CREATE UNIQUE INDEX "IX_roles_rol_guid" ON roles (rol_guid);

CREATE UNIQUE INDEX "IX_usuario_usu_guid" ON usuario (usu_guid);

CREATE UNIQUE INDEX "IX_usuario_usu_login" ON usuario (usu_login);

CREATE INDEX "IX_usuarioxroles_rol_id" ON usuarioxroles (rol_id);

CREATE UNIQUE INDEX "IX_usuarioxroles_usu_id_rol_id" ON usuarioxroles (usu_id, rol_id);

SELECT setval(
    pg_get_serial_sequence('roles', 'rol_id'),
    GREATEST(
        (SELECT MAX(rol_id) FROM roles) + 1,
        nextval(pg_get_serial_sequence('roles', 'rol_id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515012844_InitialIdentidadSchema', '10.0.4');

COMMIT;

