// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelDreams.MsReservas.DataAccess.Context;

#nullable disable

namespace TravelDreams.MsReservas.DataAccess.Migrations
{
    [DbContext(typeof(ReservasDbContext))]
    partial class ReservasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Property<int>("cli_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cli_id"));

                    b.Property<string>("cli_apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cli_correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("cli_direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("cli_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("cli_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("cli_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("cli_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("cli_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cli_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cli_nombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cli_numero_identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("cli_razon_social")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("cli_row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("cli_telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("cli_tipo_identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("cli_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cli_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("usu_guid")
                        .HasColumnType("uuid");

                    b.HasKey("cli_id");

                    b.HasIndex("cli_guid")
                        .IsUnique();

                    b.HasIndex("cli_numero_identificacion")
                        .IsUnique();

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_estado", "cli_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_clientes_tipo_id", "cli_tipo_identificacion IN ('CC','RUC','PASAPORTE','CEDULA','OTRO')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaDetalleEntity", b =>
                {
                    b.Property<int>("rdet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rdet_id"));

                    b.Property<int>("rdet_cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("rdet_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime>("rdet_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rdet_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rdet_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<decimal>("rdet_precio_unit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("rdet_subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("rdet_ticket_titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("rdet_tipo_participante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("rdet_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("tck_guid")
                        .HasColumnType("uuid");

                    b.HasKey("rdet_id");

                    b.HasIndex("rdet_guid")
                        .IsUnique();

                    b.HasIndex("rev_id", "tck_guid")
                        .IsUnique();

                    b.ToTable("reserva_detalle", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Property<int>("rev_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rev_id"));

                    b.Property<Guid>("at_guid")
                        .HasColumnType("uuid");

                    b.Property<int>("cli_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("hor_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("rev_atraccion_nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("rev_codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("rev_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime?>("rev_fecha_cancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rev_fecha_expiracion_utc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("rev_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rev_fecha_reserva_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("rev_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("rev_hor_fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("rev_hor_hora_fin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("rev_hor_hora_inicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("rev_ip_cancelacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rev_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rev_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rev_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("rev_motivo_cancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("rev_origen_canal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("rev_subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("rev_total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("rev_usuario_cancelacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rev_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rev_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("rev_valor_iva")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("rev_id");

                    b.HasIndex("at_guid");

                    b.HasIndex("cli_id");

                    b.HasIndex("hor_guid");

                    b.HasIndex("rev_codigo")
                        .IsUnique();

                    b.HasIndex("rev_guid")
                        .IsUnique();

                    b.ToTable("reservas", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservas_estado", "rev_estado IN ('PENDIENTE','PAGADA','CONFIRMADA','CANCELADA','EXPIRADA','USADA','NO_SHOW')");

                            t.HasCheckConstraint("ck_reservas_iva", "rev_valor_iva >= 0");

                            t.HasCheckConstraint("ck_reservas_subtotal", "rev_subtotal >= 0");

                            t.HasCheckConstraint("ck_reservas_total", "rev_total >= 0");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaEstadoHistorialEntity", b =>
                {
                    b.Property<int>("reh_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reh_id"));

                    b.Property<string>("reh_estado_anterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("reh_estado_nuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("reh_fecha_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("reh_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("reh_ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("reh_observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("reh_usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("rev_id")
                        .HasColumnType("integer");

                    b.HasKey("reh_id");

                    b.HasIndex("reh_guid")
                        .IsUnique();

                    b.HasIndex("rev_id");

                    b.ToTable("reserva_estado_historial", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.V3.MarketplaceReservaSolicitudV3Entity", b =>
                {
                    b.Property<long>("rsol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("rsol_id"));

                    b.Property<Guid>("cli_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("rev_codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("rev_guid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("rsol_correlation_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("rsol_created_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("rsol_error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("rsol_estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("rsol_payload_json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("rsol_updated_at_utc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("rsol_id");

                    b.HasIndex("cli_guid");

                    b.HasIndex("rsol_correlation_id")
                        .IsUnique();

                    b.HasIndex("rsol_estado");

                    b.ToTable("reservas_solicitudes_v3", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaDetalleEntity", b =>
                {
                    b.HasOne("TravelDreams.MsReservas.DataAccess.Entities.ReservaEntity", "Reserva")
                        .WithMany("Detalles")
                        .HasForeignKey("rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.HasOne("TravelDreams.MsReservas.DataAccess.Entities.ClienteEntity", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("cli_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaEstadoHistorialEntity", b =>
                {
                    b.HasOne("TravelDreams.MsReservas.DataAccess.Entities.ReservaEntity", "Reserva")
                        .WithMany("EstadoHistorial")
                        .HasForeignKey("rev_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("TravelDreams.MsReservas.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("EstadoHistorial");
                });
#pragma warning restore 612, 618
        }
    }
}
