CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE clientes (
    cli_id integer GENERATED BY DEFAULT AS IDENTITY,
    cli_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    usu_guid uuid,
    cli_tipo_identificacion character varying(20) NOT NULL,
    cli_numero_identificacion character varying(20) NOT NULL,
    cli_nombres character varying(100),
    cli_apellidos character varying(100),
    cli_razon_social character varying(200),
    cli_correo character varying(150) NOT NULL,
    cli_telefono character varying(20),
    cli_direccion character varying(300),
    cli_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    cli_usuario_ingreso character varying(100) NOT NULL,
    cli_ip_ingreso character varying(45) NOT NULL,
    cli_fecha_eliminacion timestamp with time zone,
    cli_usuario_eliminacion character varying(100),
    cli_ip_eliminacion character varying(45),
    cli_estado character(1) NOT NULL DEFAULT 'A',
    cli_row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_clientes" PRIMARY KEY (cli_id),
    CONSTRAINT ck_clientes_estado CHECK (cli_estado IN ('A','I')),
    CONSTRAINT ck_clientes_tipo_id CHECK (cli_tipo_identificacion IN ('CC','RUC','PASAPORTE','CEDULA','OTRO'))
);

CREATE TABLE reservas (
    rev_id integer GENERATED BY DEFAULT AS IDENTITY,
    rev_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    rev_codigo character varying(20) NOT NULL,
    cli_id integer NOT NULL,
    at_guid uuid NOT NULL,
    hor_guid uuid NOT NULL,
    rev_fecha_reserva_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    rev_fecha_expiracion_utc timestamp with time zone NOT NULL,
    rev_subtotal numeric(10,2) NOT NULL,
    rev_valor_iva numeric(10,2) NOT NULL,
    rev_total numeric(10,2) NOT NULL,
    rev_moneda character(3) NOT NULL DEFAULT 'USD',
    rev_origen_canal character varying(50),
    rev_usuario_ingreso character varying(100) NOT NULL,
    rev_ip_ingreso character varying(45) NOT NULL,
    rev_fecha_mod timestamp with time zone,
    rev_usuario_mod character varying(100),
    rev_ip_mod character varying(45),
    rev_fecha_cancelacion timestamp with time zone,
    rev_usuario_cancelacion character varying(100),
    rev_ip_cancelacion character varying(45),
    rev_motivo_cancelacion character varying(300),
    rev_estado character varying(20) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT "PK_reservas" PRIMARY KEY (rev_id),
    CONSTRAINT ck_reservas_estado CHECK (rev_estado IN ('PENDIENTE','PAGADA','CONFIRMADA','CANCELADA','EXPIRADA','USADA','NO_SHOW')),
    CONSTRAINT ck_reservas_iva CHECK (rev_valor_iva >= 0),
    CONSTRAINT ck_reservas_subtotal CHECK (rev_subtotal >= 0),
    CONSTRAINT ck_reservas_total CHECK (rev_total >= 0),
    CONSTRAINT "FK_reservas_clientes_cli_id" FOREIGN KEY (cli_id) REFERENCES clientes (cli_id) ON DELETE CASCADE
);

CREATE TABLE reserva_detalle (
    rdet_id integer GENERATED BY DEFAULT AS IDENTITY,
    rdet_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    rev_id integer NOT NULL,
    tck_guid uuid NOT NULL,
    rdet_ticket_titulo character varying(150) NOT NULL,
    rdet_tipo_participante character varying(30) NOT NULL,
    rdet_cantidad integer NOT NULL,
    rdet_precio_unit numeric(10,2) NOT NULL,
    rdet_subtotal numeric(10,2) NOT NULL,
    rdet_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    rdet_usuario_ingreso character varying(100) NOT NULL,
    rdet_ip_ingreso character varying(45) NOT NULL,
    rdet_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_reserva_detalle" PRIMARY KEY (rdet_id),
    CONSTRAINT "FK_reserva_detalle_reservas_rev_id" FOREIGN KEY (rev_id) REFERENCES reservas (rev_id) ON DELETE CASCADE
);

CREATE TABLE reserva_estado_historial (
    reh_id integer GENERATED BY DEFAULT AS IDENTITY,
    reh_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    rev_id integer NOT NULL,
    reh_estado_anterior character varying(20),
    reh_estado_nuevo character varying(20) NOT NULL,
    reh_fecha_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    reh_usuario character varying(100) NOT NULL,
    reh_ip character varying(45) NOT NULL,
    reh_observacion character varying(300),
    CONSTRAINT "PK_reserva_estado_historial" PRIMARY KEY (reh_id),
    CONSTRAINT "FK_reserva_estado_historial_reservas_rev_id" FOREIGN KEY (rev_id) REFERENCES reservas (rev_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_clientes_cli_guid" ON clientes (cli_guid);

CREATE UNIQUE INDEX "IX_clientes_cli_numero_identificacion" ON clientes (cli_numero_identificacion);

CREATE UNIQUE INDEX "IX_reserva_detalle_rdet_guid" ON reserva_detalle (rdet_guid);

CREATE UNIQUE INDEX "IX_reserva_detalle_rev_id_tck_guid" ON reserva_detalle (rev_id, tck_guid);

CREATE UNIQUE INDEX "IX_reserva_estado_historial_reh_guid" ON reserva_estado_historial (reh_guid);

CREATE INDEX "IX_reserva_estado_historial_rev_id" ON reserva_estado_historial (rev_id);

CREATE INDEX "IX_reservas_at_guid" ON reservas (at_guid);

CREATE INDEX "IX_reservas_cli_id" ON reservas (cli_id);

CREATE INDEX "IX_reservas_hor_guid" ON reservas (hor_guid);

CREATE UNIQUE INDEX "IX_reservas_rev_codigo" ON reservas (rev_codigo);

CREATE UNIQUE INDEX "IX_reservas_rev_guid" ON reservas (rev_guid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514152309_InitialReservasSchema', '10.0.4');

COMMIT;

