CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE categoria (
    cat_id integer GENERATED BY DEFAULT AS IDENTITY,
    cat_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    cat_parent_id integer,
    cat_nombre character varying(100) NOT NULL,
    cat_tagname character varying(80),
    cat_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    cat_usuario_ingreso character varying(100) NOT NULL,
    cat_ip_ingreso character varying(45) NOT NULL,
    cat_fecha_mod timestamp with time zone,
    cat_usuario_mod character varying(100),
    cat_ip_mod character varying(45),
    cat_fecha_eliminacion timestamp with time zone,
    cat_usuario_eliminacion character varying(100),
    cat_ip_eliminacion character varying(45),
    cat_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_categoria" PRIMARY KEY (cat_id),
    CONSTRAINT ck_categoria_estado CHECK (cat_estado IN ('A','I')),
    CONSTRAINT ck_categoria_selfref CHECK (cat_parent_id IS NULL OR cat_parent_id <> cat_id),
    CONSTRAINT "FK_categoria_categoria_cat_parent_id" FOREIGN KEY (cat_parent_id) REFERENCES categoria (cat_id)
);

CREATE TABLE destino (
    des_id integer GENERATED BY DEFAULT AS IDENTITY,
    des_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    des_nombre character varying(150) NOT NULL,
    des_pais character varying(100) NOT NULL,
    des_imagen_url character varying(500),
    des_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    des_usuario_ingreso character varying(100) NOT NULL,
    des_ip_ingreso character varying(45) NOT NULL,
    des_fecha_mod timestamp with time zone,
    des_usuario_mod character varying(100),
    des_ip_mod character varying(45),
    des_fecha_eliminacion timestamp with time zone,
    des_usuario_eliminacion character varying(100),
    des_ip_eliminacion character varying(45),
    des_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_destino" PRIMARY KEY (des_id),
    CONSTRAINT ck_destino_estado CHECK (des_estado IN ('A','I'))
);

CREATE TABLE idioma (
    id_id integer GENERATED BY DEFAULT AS IDENTITY,
    id_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    id_codigo character varying(10) NOT NULL,
    id_descripcion character varying(80) NOT NULL,
    id_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    id_usuario_ingreso character varying(100) NOT NULL,
    id_ip_ingreso character varying(45) NOT NULL,
    id_fecha_mod timestamp with time zone,
    id_usuario_mod character varying(100),
    id_ip_mod character varying(45),
    id_fecha_eliminacion timestamp with time zone,
    id_usuario_eliminacion character varying(100),
    id_ip_eliminacion character varying(45),
    id_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_idioma" PRIMARY KEY (id_id),
    CONSTRAINT ck_idioma_estado CHECK (id_estado IN ('A','I'))
);

CREATE TABLE imagen (
    img_id integer GENERATED BY DEFAULT AS IDENTITY,
    img_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    img_url character varying(500) NOT NULL,
    img_descripcion character varying(200),
    img_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    img_usuario_ingreso character varying(100) NOT NULL,
    img_ip_ingreso character varying(45) NOT NULL,
    img_fecha_mod timestamp with time zone,
    img_usuario_mod character varying(100),
    img_ip_mod character varying(45),
    img_fecha_eliminacion timestamp with time zone,
    img_usuario_eliminacion character varying(100),
    img_ip_eliminacion character varying(45),
    img_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_imagen" PRIMARY KEY (img_id),
    CONSTRAINT ck_imagen_estado CHECK (img_estado IN ('A','I'))
);

CREATE TABLE incluye (
    inc_id integer GENERATED BY DEFAULT AS IDENTITY,
    inc_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    inc_descripcion character varying(200) NOT NULL,
    inc_tipo character varying(20) NOT NULL DEFAULT 'INCLUYE',
    inc_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_incluye" PRIMARY KEY (inc_id),
    CONSTRAINT ck_incluye_estado CHECK (inc_estado IN ('A','I')),
    CONSTRAINT ck_incluye_tipo CHECK (inc_tipo IN ('INCLUYE','NO_INCLUYE','ETIQUETA'))
);

CREATE TABLE atraccion (
    at_id integer GENERATED BY DEFAULT AS IDENTITY,
    at_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    des_id integer NOT NULL,
    at_num_establecimiento character varying(30),
    at_nombre character varying(200) NOT NULL,
    at_descripcion character varying(2000),
    at_total_resenias integer NOT NULL DEFAULT 0,
    at_direccion character varying(300),
    at_duracion_minutos integer,
    at_punto_encuentro character varying(300),
    at_precio_referencia numeric(10,2),
    at_incluye_acompaniante boolean NOT NULL DEFAULT FALSE,
    at_incluye_transporte boolean NOT NULL DEFAULT FALSE,
    at_disponible boolean NOT NULL DEFAULT TRUE,
    at_free_cancellation boolean NOT NULL DEFAULT FALSE,
    at_skip_the_line boolean NOT NULL DEFAULT FALSE,
    at_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    at_usuario_ingreso character varying(100) NOT NULL,
    at_ip_ingreso character varying(45) NOT NULL,
    at_fecha_mod timestamp with time zone,
    at_usuario_mod character varying(100),
    at_ip_mod character varying(45),
    at_fecha_eliminacion timestamp with time zone,
    at_usuario_eliminacion character varying(100),
    at_ip_eliminacion character varying(45),
    at_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_atraccion" PRIMARY KEY (at_id),
    CONSTRAINT ck_atraccion_duracion CHECK (at_duracion_minutos IS NULL OR at_duracion_minutos > 0),
    CONSTRAINT ck_atraccion_estado CHECK (at_estado IN ('A','I')),
    CONSTRAINT ck_atraccion_precio CHECK (at_precio_referencia IS NULL OR at_precio_referencia >= 0),
    CONSTRAINT ck_atraccion_resenias CHECK (at_total_resenias >= 0),
    CONSTRAINT "FK_atraccion_destino_des_id" FOREIGN KEY (des_id) REFERENCES destino (des_id) ON DELETE CASCADE
);

CREATE TABLE atraccion_incluye (
    inc_id integer NOT NULL,
    at_id integer NOT NULL,
    ai_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ai_usuario_ingreso character varying(100) NOT NULL,
    ai_fecha_eliminacion timestamp with time zone,
    ai_usuario_eliminacion character varying(100),
    ai_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_atraccion_incluye" PRIMARY KEY (inc_id, at_id),
    CONSTRAINT "FK_atraccion_incluye_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE,
    CONSTRAINT "FK_atraccion_incluye_incluye_inc_id" FOREIGN KEY (inc_id) REFERENCES incluye (inc_id) ON DELETE CASCADE
);

CREATE TABLE categoria_atraccion (
    cat_id integer NOT NULL,
    at_id integer NOT NULL,
    ca_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ca_usuario_ingreso character varying(100) NOT NULL,
    ca_fecha_eliminacion timestamp with time zone,
    ca_usuario_eliminacion character varying(100),
    ca_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_categoria_atraccion" PRIMARY KEY (cat_id, at_id),
    CONSTRAINT "FK_categoria_atraccion_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE,
    CONSTRAINT "FK_categoria_atraccion_categoria_cat_id" FOREIGN KEY (cat_id) REFERENCES categoria (cat_id) ON DELETE CASCADE
);

CREATE TABLE horario (
    hor_id integer GENERATED BY DEFAULT AS IDENTITY,
    hor_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    at_id integer NOT NULL,
    hor_fecha date NOT NULL,
    hor_hora_inicio time without time zone NOT NULL,
    hor_hora_fin time without time zone,
    hor_cupos_disponibles integer NOT NULL,
    hor_dias_semana character varying(20) NOT NULL DEFAULT '0,1,2,3,4,5,6',
    hor_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    hor_usuario_ingreso character varying(100) NOT NULL,
    hor_ip_ingreso character varying(45) NOT NULL,
    hor_fecha_mod timestamp with time zone,
    hor_usuario_mod character varying(100),
    hor_ip_mod character varying(45),
    hor_fecha_eliminacion timestamp with time zone,
    hor_usuario_eliminacion character varying(100),
    hor_ip_eliminacion character varying(45),
    hor_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_horario" PRIMARY KEY (hor_id),
    CONSTRAINT ck_horario_cupos CHECK (hor_cupos_disponibles >= 0),
    CONSTRAINT ck_horario_estado CHECK (hor_estado IN ('A','I')),
    CONSTRAINT "FK_horario_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE
);

CREATE TABLE idioma_atraccion (
    id_id integer NOT NULL,
    at_id integer NOT NULL,
    ia_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ia_usuario_ingreso character varying(100) NOT NULL,
    ia_fecha_eliminacion timestamp with time zone,
    ia_usuario_eliminacion character varying(100),
    ia_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_idioma_atraccion" PRIMARY KEY (id_id, at_id),
    CONSTRAINT "FK_idioma_atraccion_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE,
    CONSTRAINT "FK_idioma_atraccion_idioma_id_id" FOREIGN KEY (id_id) REFERENCES idioma (id_id) ON DELETE CASCADE
);

CREATE TABLE imagen_atraccion (
    img_id integer NOT NULL,
    at_id integer NOT NULL,
    ima_es_principal boolean NOT NULL DEFAULT FALSE,
    ima_orden integer NOT NULL DEFAULT 0,
    ima_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ima_usuario_ingreso character varying(100) NOT NULL,
    ima_fecha_eliminacion timestamp with time zone,
    ima_usuario_eliminacion character varying(100),
    ima_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_imagen_atraccion" PRIMARY KEY (img_id, at_id),
    CONSTRAINT "FK_imagen_atraccion_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE,
    CONSTRAINT "FK_imagen_atraccion_imagen_img_id" FOREIGN KEY (img_id) REFERENCES imagen (img_id) ON DELETE CASCADE
);

CREATE TABLE resenia (
    rsn_id integer GENERATED BY DEFAULT AS IDENTITY,
    rsn_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    at_id integer NOT NULL,
    rev_guid uuid NOT NULL,
    rsn_comentario character varying(1000),
    rsn_rating smallint NOT NULL,
    rsn_fecha_creacion timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    rsn_usuario_creacion character varying(100) NOT NULL,
    rsn_ip_creacion character varying(45) NOT NULL,
    rsn_fecha_mod timestamp with time zone,
    rsn_usuario_mod character varying(100),
    rsn_ip_mod character varying(45),
    rsn_fecha_eliminacion timestamp with time zone,
    rsn_usuario_eliminacion character varying(100),
    rsn_ip_eliminacion character varying(45),
    rsn_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_resenia" PRIMARY KEY (rsn_id),
    CONSTRAINT ck_resenia_estado CHECK (rsn_estado IN ('A','I')),
    CONSTRAINT ck_resenia_rating CHECK (rsn_rating BETWEEN 1 AND 5),
    CONSTRAINT "FK_resenia_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE
);

CREATE TABLE ticket (
    tck_id integer GENERATED BY DEFAULT AS IDENTITY,
    tck_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    at_id integer NOT NULL,
    tck_titulo character varying(150) NOT NULL,
    tck_precio numeric(10,2) NOT NULL,
    tck_moneda character(3) NOT NULL DEFAULT 'USD',
    tck_tipo_participante character varying(30) NOT NULL DEFAULT 'Adulto',
    tck_capacidad_maxima integer NOT NULL,
    tck_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    tck_usuario_ingreso character varying(100) NOT NULL,
    tck_ip_ingreso character varying(45) NOT NULL,
    tck_fecha_mod timestamp with time zone,
    tck_usuario_mod character varying(100),
    tck_ip_mod character varying(45),
    tck_fecha_eliminacion timestamp with time zone,
    tck_usuario_eliminacion character varying(100),
    tck_ip_eliminacion character varying(45),
    tck_estado character(1) NOT NULL DEFAULT 'A',
    CONSTRAINT "PK_ticket" PRIMARY KEY (tck_id),
    CONSTRAINT ck_ticket_capacidad CHECK (tck_capacidad_maxima > 0),
    CONSTRAINT ck_ticket_estado CHECK (tck_estado IN ('A','I')),
    CONSTRAINT ck_ticket_precio CHECK (tck_precio >= 0),
    CONSTRAINT "FK_ticket_atraccion_at_id" FOREIGN KEY (at_id) REFERENCES atraccion (at_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_atraccion_at_guid" ON atraccion (at_guid);

CREATE INDEX "IX_atraccion_at_nombre" ON atraccion (at_nombre);

CREATE INDEX "IX_atraccion_des_id" ON atraccion (des_id);

CREATE INDEX "IX_atraccion_incluye_at_id" ON atraccion_incluye (at_id);

CREATE UNIQUE INDEX "IX_categoria_cat_guid" ON categoria (cat_guid);

CREATE INDEX "IX_categoria_cat_parent_id" ON categoria (cat_parent_id);

CREATE INDEX "IX_categoria_cat_tagname" ON categoria (cat_tagname);

CREATE INDEX "IX_categoria_atraccion_at_id" ON categoria_atraccion (at_id);

CREATE UNIQUE INDEX "IX_destino_des_guid" ON destino (des_guid);

CREATE INDEX "IX_destino_des_pais" ON destino (des_pais);

CREATE UNIQUE INDEX "IX_horario_at_id_hor_fecha_hor_hora_inicio" ON horario (at_id, hor_fecha, hor_hora_inicio);

CREATE UNIQUE INDEX "IX_horario_hor_guid" ON horario (hor_guid);

CREATE UNIQUE INDEX "IX_idioma_id_codigo" ON idioma (id_codigo);

CREATE UNIQUE INDEX "IX_idioma_id_descripcion" ON idioma (id_descripcion);

CREATE UNIQUE INDEX "IX_idioma_id_guid" ON idioma (id_guid);

CREATE INDEX "IX_idioma_atraccion_at_id" ON idioma_atraccion (at_id);

CREATE UNIQUE INDEX "IX_imagen_img_guid" ON imagen (img_guid);

CREATE INDEX "IX_imagen_atraccion_at_id_ima_es_principal" ON imagen_atraccion (at_id, ima_es_principal);

CREATE UNIQUE INDEX "IX_incluye_inc_guid" ON incluye (inc_guid);

CREATE INDEX "IX_resenia_at_id" ON resenia (at_id);

CREATE UNIQUE INDEX "IX_resenia_rev_guid" ON resenia (rev_guid);

CREATE UNIQUE INDEX "IX_resenia_rsn_guid" ON resenia (rsn_guid);

CREATE INDEX "IX_ticket_at_id" ON ticket (at_id);

CREATE UNIQUE INDEX "IX_ticket_tck_guid" ON ticket (tck_guid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514144354_InitialAtraccionesSchema', '10.0.4');

COMMIT;

