-- ============================================================
--  MICROSERVICIO DE ATRACCIONES
--  Script DDL v1.0 — Creación completa del esquema
--  Conversión de SQL Server a PostgreSQL
-- ============================================================
--  Convenciones:
--    · Todas las fechas se almacenan en UTC
--    · Estado: CHAR(1) con CHECK IN ('A','I')
--    · IPs: VARCHAR(45) cubre IPv4 e IPv6
--    · GUIDs expuestos en API; IDs internos nunca expuestos
--    · Soft-delete via _estado + _fecha_eliminacion
--    · ROWVERSION en tablas con concurrencia optimista
--    · Orden de creación respeta dependencias de FK
-- ============================================================

-- PostgreSQL:
--   · No existe USE ni GO.
--   · Se crea el schema dbo para respetar los nombres del script original.
--   · Para UUID se usa gen_random_uuid() (extensión pgcrypto).
--   · ROWVERSION de SQL Server se emula con BIGINT + trigger autoincremental por UPDATE.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS dbo;

-- ============================================================
--  FUNCIONES DE APOYO
-- ============================================================

-- ============================================================
--  SECCIÓN 1: IDENTIDAD Y ACCESO
--  Orden: ROLES → USUARIO → USUARIOXROLES → CLIENTES
-- ============================================================

-- ------------------------------------------------------------
--  1.1  ROLES
-- ------------------------------------------------------------
CREATE TABLE dbo.roles (
    rol_id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    rol_guid                UUID            NOT NULL DEFAULT gen_random_uuid(),
    rol_descripcion         VARCHAR(80)     NOT NULL,

    -- Auditoría ingreso
    rol_fecha_ingreso       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rol_usuario_ingreso     VARCHAR(100)    NOT NULL,
    rol_ip_ingreso          VARCHAR(45)     NOT NULL,

    -- Auditoría eliminación lógica
    rol_fecha_eliminacion   TIMESTAMPTZ     NULL,
    rol_usuario_eliminacion VARCHAR(100)    NULL,
    rol_ip_eliminacion      VARCHAR(45)     NULL,

    -- Estado
    rol_estado              CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_roles PRIMARY KEY (rol_id),
    CONSTRAINT uk_roles_guid UNIQUE (rol_guid),
    CONSTRAINT ck_roles_estado CHECK (rol_estado IN ('A','I')),
    CONSTRAINT ck_roles_eliminacion CHECK (
        (rol_estado = 'I' AND rol_fecha_eliminacion IS NOT NULL)
        OR (rol_estado = 'A' AND rol_fecha_eliminacion IS NULL)
    )
);

-- ------------------------------------------------------------
--  1.2  USUARIO
-- ------------------------------------------------------------
CREATE TABLE dbo.usuario (
    usu_id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    usu_guid                UUID            NOT NULL DEFAULT gen_random_uuid(),
    usu_login               VARCHAR(100)    NOT NULL,
    usu_password_hash       VARCHAR(256)    NOT NULL,

    -- Auditoría registro
    usu_fecha_registro      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usu_usuario_registro    VARCHAR(100)    NOT NULL,
    usu_ip_registro         VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    usu_fecha_mod           TIMESTAMPTZ     NULL,
    usu_usuario_mod         VARCHAR(100)    NULL,
    usu_ip_mod              VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    usu_fecha_eliminacion   TIMESTAMPTZ     NULL,
    usu_usuario_eliminacion VARCHAR(100)    NULL,
    usu_ip_eliminacion      VARCHAR(45)     NULL,

    -- Estado
    usu_estado              CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_usuario PRIMARY KEY (usu_id),
    CONSTRAINT uk_usuario_guid UNIQUE (usu_guid),
    CONSTRAINT uk_usuario_login UNIQUE (usu_login),
    CONSTRAINT ck_usuario_estado CHECK (usu_estado IN ('A','I')),
    CONSTRAINT ck_usuario_eliminacion CHECK (
        (usu_estado = 'I' AND usu_fecha_eliminacion IS NOT NULL)
        OR (usu_estado = 'A' AND usu_fecha_eliminacion IS NULL)
    )
);

-- ------------------------------------------------------------
--  1.3  USUARIOXROLES
-- ------------------------------------------------------------
CREATE TABLE dbo.usuarioxroles (
    usu_rol_id              INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    usu_id                  INTEGER         NOT NULL,
    rol_id                  INTEGER         NOT NULL,
    usu_rol_estado          CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_usuarioxroles PRIMARY KEY (usu_rol_id),
    CONSTRAINT uk_usuarioxroles_par UNIQUE (usu_id, rol_id),
    CONSTRAINT ck_usuarioxroles_estado CHECK (usu_rol_estado IN ('A','I')),
    CONSTRAINT fk_usuarioxroles_usuario FOREIGN KEY (usu_id) REFERENCES dbo.usuario (usu_id),
    CONSTRAINT fk_usuarioxroles_rol FOREIGN KEY (rol_id) REFERENCES dbo.roles (rol_id)
);

-- ------------------------------------------------------------
--  1.4  CLIENTES
-- ------------------------------------------------------------
CREATE TABLE dbo.clientes (
    cli_id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    cli_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),
    usu_id                      INTEGER         NOT NULL,

    -- Datos personales / empresariales
    cli_tipo_identificacion     VARCHAR(20)     NOT NULL,
    cli_numero_identificacion   VARCHAR(20)     NOT NULL,
    cli_nombres                 VARCHAR(100)    NULL,
    cli_apellidos               VARCHAR(100)    NULL,
    cli_razon_social            VARCHAR(200)    NULL,
    cli_correo                  VARCHAR(150)    NOT NULL,
    cli_telefono                VARCHAR(20)     NULL,
    cli_direccion               VARCHAR(300)    NULL,

    -- Auditoría ingreso
    cli_fecha_ingreso           TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cli_usuario_ingreso         VARCHAR(100)    NOT NULL,
    cli_ip_ingreso              VARCHAR(45)     NOT NULL,

    -- Auditoría eliminación lógica
    cli_fecha_eliminacion       TIMESTAMPTZ     NULL,
    cli_usuario_eliminacion     VARCHAR(100)    NULL,
    cli_ip_eliminacion          VARCHAR(45)     NULL,

    -- Estado y concurrencia
    cli_estado                  CHAR(1)         NOT NULL DEFAULT 'A',
    cli_row_version             BIGINT          NOT NULL DEFAULT 1,

    -- Constraints
    CONSTRAINT pk_clientes PRIMARY KEY (cli_id),
    CONSTRAINT uk_clientes_guid UNIQUE (cli_guid),
    CONSTRAINT uk_clientes_num_identificacion UNIQUE (cli_numero_identificacion),
    CONSTRAINT ck_clientes_estado CHECK (cli_estado IN ('A','I')),
    CONSTRAINT ck_clientes_tipo_id CHECK (cli_tipo_identificacion IN ('CC','RUC','PASAPORTE','CEDULA','OTRO')),
    CONSTRAINT ck_clientes_persona CHECK (
        (cli_razon_social IS NOT NULL)
        OR (cli_nombres IS NOT NULL AND cli_apellidos IS NOT NULL)
    ),
    CONSTRAINT ck_clientes_eliminacion CHECK (
        (cli_estado = 'I' AND cli_fecha_eliminacion IS NOT NULL)
        OR (cli_estado = 'A' AND cli_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_clientes_usuario FOREIGN KEY (usu_id) REFERENCES dbo.usuario (usu_id)
);

-- ============================================================
--  SECCIÓN 2: CATÁLOGO BASE
--  Orden: DESTINO → CATEGORIA → IDIOMA → INCLUYE → IMAGEN
-- ============================================================

-- ------------------------------------------------------------
--  2.1  DESTINO
-- ------------------------------------------------------------
CREATE TABLE dbo.destino (
    des_id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    des_guid                UUID            NOT NULL DEFAULT gen_random_uuid(),
    des_nombre              VARCHAR(150)    NOT NULL,
    des_pais                VARCHAR(100)    NOT NULL,
    des_imagen_url          VARCHAR(500)    NULL,

    -- Auditoría ingreso
    des_fecha_ingreso       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    des_usuario_ingreso     VARCHAR(100)    NOT NULL,
    des_ip_ingreso          VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    des_fecha_mod           TIMESTAMPTZ     NULL,
    des_usuario_mod         VARCHAR(100)    NULL,
    des_ip_mod              VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    des_fecha_eliminacion   TIMESTAMPTZ     NULL,
    des_usuario_eliminacion VARCHAR(100)    NULL,
    des_ip_eliminacion      VARCHAR(45)     NULL,

    -- Estado
    des_estado              CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_destino PRIMARY KEY (des_id),
    CONSTRAINT uk_destino_guid UNIQUE (des_guid),
    CONSTRAINT ck_destino_estado CHECK (des_estado IN ('A','I')),
    CONSTRAINT ck_destino_eliminacion CHECK (
        (des_estado = 'I' AND des_fecha_eliminacion IS NOT NULL)
        OR (des_estado = 'A' AND des_fecha_eliminacion IS NULL)
    )
);

-- ------------------------------------------------------------
--  2.2  CATEGORIA  (auto-referencia para jerarquía)
-- ------------------------------------------------------------
CREATE TABLE dbo.categoria (
    cat_id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    cat_guid                UUID            NOT NULL DEFAULT gen_random_uuid(),
    cat_parent_id           INTEGER         NULL,       -- NULL = categoría raíz
    cat_nombre              VARCHAR(100)    NOT NULL,

    -- Auditoría ingreso
    cat_fecha_ingreso       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cat_usuario_ingreso     VARCHAR(100)    NOT NULL,
    cat_ip_ingreso          VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    cat_fecha_mod           TIMESTAMPTZ     NULL,
    cat_usuario_mod         VARCHAR(100)    NULL,
    cat_ip_mod              VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    cat_fecha_eliminacion   TIMESTAMPTZ     NULL,
    cat_usuario_eliminacion VARCHAR(100)    NULL,
    cat_ip_eliminacion      VARCHAR(45)     NULL,

    -- Estado
    cat_estado              CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_categoria PRIMARY KEY (cat_id),
    CONSTRAINT uk_categoria_guid UNIQUE (cat_guid),
    CONSTRAINT ck_categoria_estado CHECK (cat_estado IN ('A','I')),
    CONSTRAINT ck_categoria_selfref CHECK (cat_parent_id <> cat_id),
    CONSTRAINT ck_categoria_eliminacion CHECK (
        (cat_estado = 'I' AND cat_fecha_eliminacion IS NOT NULL)
        OR (cat_estado = 'A' AND cat_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_categoria_parent FOREIGN KEY (cat_parent_id) REFERENCES dbo.categoria (cat_id)
);

-- ------------------------------------------------------------
--  2.3  IDIOMA
-- ------------------------------------------------------------
CREATE TABLE dbo.idioma (
    id_id                   INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_guid                 UUID            NOT NULL DEFAULT gen_random_uuid(),
    id_descripcion          VARCHAR(80)     NOT NULL,

    -- Auditoría ingreso
    id_fecha_ingreso        TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario_ingreso      VARCHAR(100)    NOT NULL,
    id_ip_ingreso           VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    id_fecha_mod            TIMESTAMPTZ     NULL,
    id_usuario_mod          VARCHAR(100)    NULL,
    id_ip_mod               VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    id_fecha_eliminacion    TIMESTAMPTZ     NULL,
    id_usuario_eliminacion  VARCHAR(100)    NULL,
    id_ip_eliminacion       VARCHAR(45)     NULL,

    -- Estado
    id_estado               CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_idioma PRIMARY KEY (id_id),
    CONSTRAINT uk_idioma_guid UNIQUE (id_guid),
    CONSTRAINT uk_idioma_descripcion UNIQUE (id_descripcion),
    CONSTRAINT ck_idioma_estado CHECK (id_estado IN ('A','I')),
    CONSTRAINT ck_idioma_eliminacion CHECK (
        (id_estado = 'I' AND id_fecha_eliminacion IS NOT NULL)
        OR (id_estado = 'A' AND id_fecha_eliminacion IS NULL)
    )
);

-- ------------------------------------------------------------
--  2.4  INCLUYE
-- ------------------------------------------------------------
CREATE TABLE dbo.incluye (
    inc_id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    inc_guid                UUID            NOT NULL DEFAULT gen_random_uuid(),
    inc_descripcion         VARCHAR(200)    NOT NULL,
    inc_estado              CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_incluye PRIMARY KEY (inc_id),
    CONSTRAINT uk_incluye_guid UNIQUE (inc_guid),
    CONSTRAINT ck_incluye_estado CHECK (inc_estado IN ('A','I'))
);

-- ------------------------------------------------------------
--  2.5  IMAGEN
-- ------------------------------------------------------------
CREATE TABLE dbo.imagen (
    img_id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    img_guid                UUID            NOT NULL DEFAULT gen_random_uuid(),
    img_url                 VARCHAR(500)    NOT NULL,
    img_descripcion         VARCHAR(200)    NULL,

    -- Auditoría ingreso
    img_fecha_ingreso       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    img_usuario_ingreso     VARCHAR(100)    NOT NULL,
    img_ip_ingreso          VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    img_fecha_mod           TIMESTAMPTZ     NULL,
    img_usuario_mod         VARCHAR(100)    NULL,
    img_ip_mod              VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    img_fecha_eliminacion   TIMESTAMPTZ     NULL,
    img_usuario_eliminacion VARCHAR(100)    NULL,
    img_ip_eliminacion      VARCHAR(45)     NULL,

    -- Estado
    img_estado              CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_imagen PRIMARY KEY (img_id),
    CONSTRAINT uk_imagen_guid UNIQUE (img_guid),
    CONSTRAINT ck_imagen_estado CHECK (img_estado IN ('A','I')),
    CONSTRAINT ck_imagen_eliminacion CHECK (
        (img_estado = 'I' AND img_fecha_eliminacion IS NOT NULL)
        OR (img_estado = 'A' AND img_fecha_eliminacion IS NULL)
    )
);

-- ============================================================
--  SECCIÓN 3: ATRACCION Y TABLAS PIVOTE
--  Orden: ATRACCION → pivotes N:M
-- ============================================================

-- ------------------------------------------------------------
--  3.1  ATRACCION
-- ------------------------------------------------------------
CREATE TABLE dbo.atraccion (
    at_id                       INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    at_guid                     UUID            NOT NULL DEFAULT gen_random_uuid(),
    des_id                      INTEGER         NOT NULL,
    at_num_establecimiento      VARCHAR(30)     NULL,
    at_nombre                   VARCHAR(200)    NOT NULL,
    at_descripcion              VARCHAR(2000)   NULL,
    at_total_resenias           INTEGER         NOT NULL DEFAULT 0,
    at_direccion                VARCHAR(300)    NULL,
    at_duracion_minutos         INTEGER         NULL,
    at_punto_encuentro          VARCHAR(300)    NULL,
    at_precio_referencia        NUMERIC(10,2)   NULL,
    at_incluye_acompaniante     BOOLEAN         NOT NULL DEFAULT FALSE,
    at_incluye_transporte       BOOLEAN         NOT NULL DEFAULT FALSE,
    at_disponible               BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Auditoría ingreso
    at_fecha_ingreso            TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    at_usuario_ingreso          VARCHAR(100)    NOT NULL,
    at_ip_ingreso               VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    at_fecha_mod                TIMESTAMPTZ     NULL,
    at_usuario_mod              VARCHAR(100)    NULL,
    at_ip_mod                   VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    at_fecha_eliminacion        TIMESTAMPTZ     NULL,
    at_usuario_eliminacion      VARCHAR(100)    NULL,
    at_ip_eliminacion           VARCHAR(45)     NULL,

    -- Estado
    at_estado                   CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_atraccion PRIMARY KEY (at_id),
    CONSTRAINT uk_atraccion_guid UNIQUE (at_guid),
    CONSTRAINT ck_atraccion_estado CHECK (at_estado IN ('A','I')),
    CONSTRAINT ck_atraccion_precio CHECK (at_precio_referencia IS NULL OR at_precio_referencia >= 0),
    CONSTRAINT ck_atraccion_duracion CHECK (at_duracion_minutos IS NULL OR at_duracion_minutos > 0),
    CONSTRAINT ck_atraccion_resenias CHECK (at_total_resenias >= 0),
    CONSTRAINT ck_atraccion_eliminacion CHECK (
        (at_estado = 'I' AND at_fecha_eliminacion IS NOT NULL)
        OR (at_estado = 'A' AND at_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_atraccion_destino FOREIGN KEY (des_id) REFERENCES dbo.destino (des_id)
);

-- ------------------------------------------------------------
--  3.2  CATEGORIA_ATRACCION  (pivote N:M)
-- ------------------------------------------------------------
CREATE TABLE dbo.categoria_atraccion (
    cat_id                      INTEGER         NOT NULL,
    at_id                       INTEGER         NOT NULL,

    -- Auditoría
    ca_fecha_ingreso            TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ca_usuario_ingreso          VARCHAR(100)    NOT NULL,
    ca_fecha_eliminacion        TIMESTAMPTZ     NULL,
    ca_usuario_eliminacion      VARCHAR(100)    NULL,
    ca_estado                   CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_categoria_atraccion PRIMARY KEY (cat_id, at_id),
    CONSTRAINT ck_ca_estado CHECK (ca_estado IN ('A','I')),
    CONSTRAINT fk_ca_categoria FOREIGN KEY (cat_id) REFERENCES dbo.categoria (cat_id),
    CONSTRAINT fk_ca_atraccion FOREIGN KEY (at_id) REFERENCES dbo.atraccion (at_id)
);

-- ------------------------------------------------------------
--  3.3  IDIOMA_ATRACCION  (pivote N:M)
-- ------------------------------------------------------------
CREATE TABLE dbo.idioma_atraccion (
    id_id                       INTEGER         NOT NULL,
    at_id                       INTEGER         NOT NULL,

    -- Auditoría
    ia_fecha_ingreso            TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ia_usuario_ingreso          VARCHAR(100)    NOT NULL,
    ia_fecha_eliminacion        TIMESTAMPTZ     NULL,
    ia_usuario_eliminacion      VARCHAR(100)    NULL,
    ia_estado                   CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_idioma_atraccion PRIMARY KEY (id_id, at_id),
    CONSTRAINT ck_ia_estado CHECK (ia_estado IN ('A','I')),
    CONSTRAINT fk_ia_idioma FOREIGN KEY (id_id) REFERENCES dbo.idioma (id_id),
    CONSTRAINT fk_ia_atraccion FOREIGN KEY (at_id) REFERENCES dbo.atraccion (at_id)
);

-- ------------------------------------------------------------
--  3.4  IMAGEN_ATRACCION  (pivote N:M)
-- ------------------------------------------------------------
CREATE TABLE dbo.imagen_atraccion (
    img_id                      INTEGER         NOT NULL,
    at_id                       INTEGER         NOT NULL,

    -- Auditoría
    ima_fecha_ingreso           TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ima_usuario_ingreso         VARCHAR(100)    NOT NULL,
    ima_fecha_eliminacion       TIMESTAMPTZ     NULL,
    ima_usuario_eliminacion     VARCHAR(100)    NULL,
    ima_estado                  CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_imagen_atraccion PRIMARY KEY (img_id, at_id),
    CONSTRAINT ck_ima_estado CHECK (ima_estado IN ('A','I')),
    CONSTRAINT fk_ima_imagen FOREIGN KEY (img_id) REFERENCES dbo.imagen (img_id),
    CONSTRAINT fk_ima_atraccion FOREIGN KEY (at_id) REFERENCES dbo.atraccion (at_id)
);

-- ------------------------------------------------------------
--  3.5  ATRACCION_INCLUYE  (pivote N:M)
-- ------------------------------------------------------------
CREATE TABLE dbo.atraccion_incluye (
    inc_id                      INTEGER         NOT NULL,
    at_id                       INTEGER         NOT NULL,

    -- Auditoría
    ai_fecha_ingreso            TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ai_usuario_ingreso          VARCHAR(100)    NOT NULL,
    ai_fecha_eliminacion        TIMESTAMPTZ     NULL,
    ai_usuario_eliminacion      VARCHAR(100)    NULL,
    ai_estado                   CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_atraccion_incluye PRIMARY KEY (inc_id, at_id),
    CONSTRAINT ck_ai_estado CHECK (ai_estado IN ('A','I')),
    CONSTRAINT fk_ai_incluye FOREIGN KEY (inc_id) REFERENCES dbo.incluye (inc_id),
    CONSTRAINT fk_ai_atraccion FOREIGN KEY (at_id) REFERENCES dbo.atraccion (at_id)
);

-- ============================================================
--  SECCIÓN 4: DISPONIBILIDAD
--  Orden: TICKET → HORARIO
-- ============================================================

-- ------------------------------------------------------------
--  4.1  TICKET
-- ------------------------------------------------------------
CREATE TABLE dbo.ticket (
    tck_id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    tck_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),
    at_id                       INTEGER         NOT NULL,
    tck_titulo                  VARCHAR(150)    NOT NULL,
    tck_precio                  NUMERIC(10,2)   NOT NULL,
    tck_tipo_participante       VARCHAR(30)     NOT NULL DEFAULT 'Adulto',
    tck_capacidad_maxima        INTEGER         NOT NULL,
    tck_cupos_disponibles       INTEGER         NOT NULL,

    -- Auditoría ingreso
    tck_fecha_ingreso           TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tck_usuario_ingreso         VARCHAR(100)    NOT NULL,
    tck_ip_ingreso              VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    tck_fecha_mod               TIMESTAMPTZ     NULL,
    tck_usuario_mod             VARCHAR(100)    NULL,
    tck_ip_mod                  VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    tck_fecha_eliminacion       TIMESTAMPTZ     NULL,
    tck_usuario_eliminacion     VARCHAR(100)    NULL,
    tck_ip_eliminacion          VARCHAR(45)     NULL,

    -- Estado
    tck_estado                  CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_ticket PRIMARY KEY (tck_id),
    CONSTRAINT uk_ticket_guid UNIQUE (tck_guid),
    CONSTRAINT ck_ticket_estado CHECK (tck_estado IN ('A','I')),
    CONSTRAINT ck_ticket_precio CHECK (tck_precio >= 0),
    CONSTRAINT ck_ticket_capacidad CHECK (tck_capacidad_maxima > 0),
    CONSTRAINT ck_ticket_cupos CHECK (
        tck_cupos_disponibles >= 0
        AND tck_cupos_disponibles <= tck_capacidad_maxima
    ),
    CONSTRAINT ck_ticket_tipo_participante CHECK (tck_tipo_participante IN ('Adulto','Niño','Grupo','Estudiante','Senior')),
    CONSTRAINT ck_ticket_eliminacion CHECK (
        (tck_estado = 'I' AND tck_fecha_eliminacion IS NOT NULL)
        OR (tck_estado = 'A' AND tck_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_ticket_atraccion FOREIGN KEY (at_id) REFERENCES dbo.atraccion (at_id)
);

-- ------------------------------------------------------------
--  4.2  HORARIO
-- ------------------------------------------------------------
CREATE TABLE dbo.horario (
    hor_id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    hor_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),
    tck_id                      INTEGER         NOT NULL,
    hor_fecha                   DATE            NOT NULL,
    hor_hora_inicio             TIME            NOT NULL,
    hor_hora_fin                TIME            NULL,
    hor_cupos_disponibles       INTEGER         NOT NULL,

    -- Auditoría ingreso
    hor_fecha_ingreso           TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hor_usuario_ingreso         VARCHAR(100)    NOT NULL,
    hor_ip_ingreso              VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    hor_fecha_mod               TIMESTAMPTZ     NULL,
    hor_usuario_mod             VARCHAR(100)    NULL,
    hor_ip_mod                  VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    hor_fecha_eliminacion       TIMESTAMPTZ     NULL,
    hor_usuario_eliminacion     VARCHAR(100)    NULL,
    hor_ip_eliminacion          VARCHAR(45)     NULL,

    -- Estado
    hor_estado                  CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_horario PRIMARY KEY (hor_id),
    CONSTRAINT uk_horario_guid UNIQUE (hor_guid),
    CONSTRAINT uk_horario_slot UNIQUE (tck_id, hor_fecha, hor_hora_inicio),
    CONSTRAINT ck_horario_estado CHECK (hor_estado IN ('A','I')),
    CONSTRAINT ck_horario_cupos CHECK (hor_cupos_disponibles >= 0),
    CONSTRAINT ck_horario_horas CHECK (hor_hora_fin IS NULL OR hor_hora_fin > hor_hora_inicio),
    CONSTRAINT ck_horario_fecha CHECK (hor_fecha >= CURRENT_DATE),
    CONSTRAINT ck_horario_eliminacion CHECK (
        (hor_estado = 'I' AND hor_fecha_eliminacion IS NOT NULL)
        OR (hor_estado = 'A' AND hor_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_horario_ticket FOREIGN KEY (tck_id) REFERENCES dbo.ticket (tck_id)
);

-- ============================================================
--  SECCIÓN 5: RESEÑAS
-- ============================================================

-- ------------------------------------------------------------
--  5.1  RESEÑA  (depende de ATRACCION y RESERVAS — RESERVAS
--               se crea en sección 6, por eso FK se agrega
--               al final con ALTER TABLE)
-- ------------------------------------------------------------
CREATE TABLE dbo.resenia (
    rsn_id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    rsn_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),
    at_id                       INTEGER         NOT NULL,
    rev_id                      INTEGER         NOT NULL,
    rsn_comentario              VARCHAR(1000)   NULL,
    rsn_rating                  SMALLINT        NOT NULL,

    -- Auditoría creación
    rsn_fecha_creacion          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rsn_usuario_creacion        VARCHAR(100)    NOT NULL,
    rsn_ip_creacion             VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    rsn_fecha_mod               TIMESTAMPTZ     NULL,
    rsn_usuario_mod             VARCHAR(100)    NULL,
    rsn_ip_mod                  VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    rsn_fecha_eliminacion       TIMESTAMPTZ     NULL,
    rsn_usuario_eliminacion     VARCHAR(100)    NULL,
    rsn_ip_eliminacion          VARCHAR(45)     NULL,

    -- Estado
    rsn_estado                  CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_resenia PRIMARY KEY (rsn_id),
    CONSTRAINT uk_resenia_guid UNIQUE (rsn_guid),
    CONSTRAINT uk_resenia_reserva UNIQUE (rev_id),
    CONSTRAINT ck_resenia_estado CHECK (rsn_estado IN ('A','I')),
    CONSTRAINT ck_resenia_rating CHECK (rsn_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_resenia_eliminacion CHECK (
        (rsn_estado = 'I' AND rsn_fecha_eliminacion IS NOT NULL)
        OR (rsn_estado = 'A' AND rsn_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_resenia_atraccion FOREIGN KEY (at_id) REFERENCES dbo.atraccion (at_id)
);

-- ============================================================
--  SECCIÓN 6: RESERVAS Y FACTURACIÓN
-- ============================================================

-- ------------------------------------------------------------
--  6.1  RESERVAS  (cabecera)
-- ------------------------------------------------------------
CREATE TABLE dbo.reservas (
    rev_id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    rev_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),
    rev_codigo                  VARCHAR(20)     NOT NULL,
    cli_id                      INTEGER         NOT NULL,
    hor_id                      INTEGER         NOT NULL,
    rev_fecha_reserva_utc       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Financiero (totales calculados desde RESERVA_DETALLE)
    rev_subtotal                NUMERIC(10,2)   NOT NULL,
    rev_valor_iva               NUMERIC(10,2)   NOT NULL,
    rev_total                   NUMERIC(10,2)   NOT NULL,
    rev_origen_canal            VARCHAR(50)     NULL,

    -- Auditoría ingreso
    rev_usuario_ingreso         VARCHAR(100)    NOT NULL,
    rev_ip_ingreso              VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    rev_fecha_mod               TIMESTAMPTZ     NULL,
    rev_usuario_mod             VARCHAR(100)    NULL,
    rev_ip_mod                  VARCHAR(45)     NULL,

    -- Auditoría cancelación
    rev_fecha_cancelacion       TIMESTAMPTZ     NULL,
    rev_usuario_cancelacion     VARCHAR(100)    NULL,
    rev_ip_cancelacion          VARCHAR(45)     NULL,
    rev_motivo_cancelacion      VARCHAR(300)    NULL,

    -- Estado
    rev_estado                  CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_reservas PRIMARY KEY (rev_id),
    CONSTRAINT uk_reservas_guid UNIQUE (rev_guid),
    CONSTRAINT uk_reservas_codigo UNIQUE (rev_codigo),
    CONSTRAINT ck_reservas_estado CHECK (rev_estado IN ('A','I','C')),
    CONSTRAINT ck_reservas_subtotal CHECK (rev_subtotal >= 0),
    CONSTRAINT ck_reservas_iva CHECK (rev_valor_iva >= 0),
    CONSTRAINT ck_reservas_total CHECK (rev_total >= 0),
    CONSTRAINT ck_reservas_total_coherente CHECK (rev_total = rev_subtotal + rev_valor_iva),
    CONSTRAINT ck_reservas_cancelacion CHECK (
        (rev_estado = 'C' AND rev_fecha_cancelacion IS NOT NULL AND rev_motivo_cancelacion IS NOT NULL)
        OR (rev_estado <> 'C' AND rev_fecha_cancelacion IS NULL)
    ),
    CONSTRAINT fk_reservas_cliente FOREIGN KEY (cli_id) REFERENCES dbo.clientes (cli_id),
    CONSTRAINT fk_reservas_horario FOREIGN KEY (hor_id) REFERENCES dbo.horario (hor_id)
);

-- ------------------------------------------------------------
--  6.2  RESERVA_DETALLE
-- ------------------------------------------------------------
CREATE TABLE dbo.reserva_detalle (
    rdet_id                     INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    rdet_guid                   UUID            NOT NULL DEFAULT gen_random_uuid(),
    rev_id                      INTEGER         NOT NULL,
    tck_id                      INTEGER         NOT NULL,

    -- Cantidad y precio congelado al momento de la reserva
    rdet_cantidad               INTEGER         NOT NULL,
    rdet_precio_unit            NUMERIC(10,2)   NOT NULL,
    rdet_subtotal               NUMERIC(10,2)   NOT NULL,

    -- Auditoría ingreso
    rdet_fecha_ingreso          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rdet_usuario_ingreso        VARCHAR(100)    NOT NULL,
    rdet_ip_ingreso             VARCHAR(45)     NOT NULL,

    -- Auditoría eliminación lógica
    rdet_fecha_eliminacion      TIMESTAMPTZ     NULL,
    rdet_usuario_eliminacion    VARCHAR(100)    NULL,
    rdet_ip_eliminacion         VARCHAR(45)     NULL,

    -- Estado
    rdet_estado                 CHAR(1)         NOT NULL DEFAULT 'A',

    -- Constraints
    CONSTRAINT pk_reserva_detalle PRIMARY KEY (rdet_id),
    CONSTRAINT uk_rdet_guid UNIQUE (rdet_guid),
    CONSTRAINT uk_rdet_rev_tck UNIQUE (rev_id, tck_id),
    CONSTRAINT ck_rdet_estado CHECK (rdet_estado IN ('A','I')),
    CONSTRAINT ck_rdet_cantidad CHECK (rdet_cantidad > 0),
    CONSTRAINT ck_rdet_precio_unit CHECK (rdet_precio_unit >= 0),
    CONSTRAINT ck_rdet_subtotal CHECK (rdet_subtotal >= 0),
    CONSTRAINT ck_rdet_subtotal_calc CHECK (rdet_subtotal = rdet_cantidad * rdet_precio_unit),
    CONSTRAINT ck_rdet_eliminacion CHECK (
        (rdet_estado = 'I' AND rdet_fecha_eliminacion IS NOT NULL)
        OR (rdet_estado = 'A' AND rdet_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_rdet_reserva FOREIGN KEY (rev_id) REFERENCES dbo.reservas (rev_id),
    CONSTRAINT fk_rdet_ticket FOREIGN KEY (tck_id) REFERENCES dbo.ticket (tck_id)
);

-- FK diferida de RESENIA → RESERVAS (ciclo roto)
ALTER TABLE dbo.resenia
    ADD CONSTRAINT fk_resenia_reserva
    FOREIGN KEY (rev_id) REFERENCES dbo.reservas (rev_id);

-- ------------------------------------------------------------
--  6.2  FACTURAS
-- ------------------------------------------------------------
CREATE TABLE dbo.facturas (
    fac_id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    fac_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),
    rev_id                      INTEGER         NOT NULL,
    fac_numero                  VARCHAR(20)     NOT NULL,
    fac_fecha_emision           TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fac_total                   NUMERIC(10,2)   NOT NULL,
    fac_observacion             VARCHAR(500)    NULL,
    fac_origen_canal            VARCHAR(50)     NULL,

    -- Auditoría ingreso
    fac_usuario_ingreso         VARCHAR(100)    NOT NULL,
    fac_ip_ingreso              VARCHAR(45)     NOT NULL,

    -- Auditoría modificación
    fac_fecha_mod               TIMESTAMPTZ     NULL,
    fac_usuario_mod             VARCHAR(100)    NULL,
    fac_ip_mod                  VARCHAR(45)     NULL,

    -- Auditoría eliminación lógica
    fac_fecha_eliminacion       TIMESTAMPTZ     NULL,
    fac_usuario_eliminacion     VARCHAR(100)    NULL,
    fac_ip_eliminacion          VARCHAR(45)     NULL,

    -- Estado y control
    fac_estado                  CHAR(1)         NOT NULL DEFAULT 'A',
    fac_motivo_inhabilitacion   VARCHAR(300)    NULL,
    fac_row_version             BIGINT          NOT NULL DEFAULT 1,

    -- Constraints
    CONSTRAINT pk_facturas PRIMARY KEY (fac_id),
    CONSTRAINT uk_facturas_guid UNIQUE (fac_guid),
    CONSTRAINT uk_facturas_numero UNIQUE (fac_numero),
    CONSTRAINT uk_facturas_reserva UNIQUE (rev_id),
    CONSTRAINT ck_facturas_estado CHECK (fac_estado IN ('A','I')),
    CONSTRAINT ck_facturas_total CHECK (fac_total >= 0),
    CONSTRAINT ck_facturas_inhabilitacion CHECK (
        (fac_estado = 'I' AND fac_motivo_inhabilitacion IS NOT NULL)
        OR (fac_estado = 'A')
    ),
    CONSTRAINT ck_facturas_eliminacion CHECK (
        (fac_estado = 'I' AND fac_fecha_eliminacion IS NOT NULL)
        OR (fac_estado = 'A' AND fac_fecha_eliminacion IS NULL)
    ),
    CONSTRAINT fk_facturas_reserva FOREIGN KEY (rev_id) REFERENCES dbo.reservas (rev_id)
);

-- ------------------------------------------------------------
--  6.3  DATOS_FACTURACION
-- ------------------------------------------------------------
CREATE TABLE dbo.datos_facturacion (
    dfac_id                     INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    dfac_guid                   UUID            NOT NULL DEFAULT gen_random_uuid(),
    fac_id                      INTEGER         NOT NULL,
    dfac_nombre                 VARCHAR(100)    NOT NULL,
    dfac_apellido               VARCHAR(100)    NULL,
    dfac_correo                 VARCHAR(150)    NOT NULL,
    dfac_telefono               VARCHAR(20)     NULL,

    -- Constraints
    CONSTRAINT pk_datos_facturacion PRIMARY KEY (dfac_id),
    CONSTRAINT uk_datos_facturacion_guid UNIQUE (dfac_guid),
    CONSTRAINT uk_datos_facturacion_fac UNIQUE (fac_id),
    CONSTRAINT ck_dfac_correo CHECK (dfac_correo LIKE '%@%.%'),
    CONSTRAINT fk_datos_facturacion_fac FOREIGN KEY (fac_id) REFERENCES dbo.facturas (fac_id)
);

-- ============================================================
--  SECCIÓN 7: AUDITORÍA TRANSVERSAL
-- ============================================================

-- ------------------------------------------------------------
--  7.1  AUDITORIA_LOG
-- ------------------------------------------------------------
CREATE TABLE dbo.auditoria_log (
    log_id                      BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    log_guid                    UUID            NOT NULL DEFAULT gen_random_uuid(),

    -- Referencia lógica (sin FK física para no romper por deletes lógicos)
    log_tabla                   VARCHAR(100)    NOT NULL,
    log_operacion               VARCHAR(20)     NOT NULL,
    log_registro_id             INTEGER         NULL,
    log_registro_guid           UUID            NULL,

    -- Snapshot de datos en JSON
    log_datos_anteriores        TEXT            NULL,
    log_datos_nuevos            TEXT            NULL,

    -- Trazabilidad
    log_fecha_utc               TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log_usuario                 VARCHAR(100)    NOT NULL,
    log_ip                      VARCHAR(45)     NOT NULL,
    log_origen_canal            VARCHAR(200)    NULL,

    -- Constraints
    CONSTRAINT pk_auditoria_log PRIMARY KEY (log_id),
    CONSTRAINT uk_auditoria_log_guid UNIQUE (log_guid),
    CONSTRAINT ck_auditoria_log_operacion CHECK (log_operacion IN ('INSERT','UPDATE','DELETE')),
    CONSTRAINT ck_auditoria_log_tabla CHECK (log_tabla IN (
        'DESTINO','CATEGORIA','IDIOMA','INCLUYE','IMAGEN',
        'ATRACCION','CATEGORIA_ATRACCION','IDIOMA_ATRACCION',
        'IMAGEN_ATRACCION','ATRACCION_INCLUYE',
        'TICKET','HORARIO','RESENIA',
        'USUARIO','ROLES','USUARIOXROLES','CLIENTES',
        'RESERVAS','FACTURAS','DATOS_FACTURACION'
    )),
    CONSTRAINT ck_auditoria_log_json_insert CHECK (
        log_operacion <> 'INSERT' OR log_datos_anteriores IS NULL
    ),
    CONSTRAINT ck_auditoria_log_json_delete CHECK (
        log_operacion <> 'DELETE' OR log_datos_nuevos IS NULL
    )
);

-- ============================================================
--  TRIGGERS PARA ROWVERSION EMULADO
-- ============================================================

CREATE OR REPLACE FUNCTION dbo.fn_increment_row_version_generic()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_ARGV[0] = 'cli_row_version' THEN
        NEW.cli_row_version := OLD.cli_row_version + 1;
    ELSIF TG_ARGV[0] = 'fac_row_version' THEN
        NEW.fac_row_version := OLD.fac_row_version + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_clientes_row_version
BEFORE UPDATE ON dbo.clientes
FOR EACH ROW
EXECUTE FUNCTION dbo.fn_increment_row_version_generic('cli_row_version');

CREATE TRIGGER trg_facturas_row_version
BEFORE UPDATE ON dbo.facturas
FOR EACH ROW
EXECUTE FUNCTION dbo.fn_increment_row_version_generic('fac_row_version');

-- ============================================================
--  SECCIÓN 8: ÍNDICES RECOMENDADOS
--  Comentados — aplicar según análisis de carga real.
--  Prefijo IX_ = índice no único, UX_ = único
-- ============================================================

-- DESTINO
-- CREATE INDEX ix_destino_pais       ON dbo.destino      (des_pais)                WHERE des_estado = 'A';

-- ATRACCION
-- CREATE INDEX ix_atraccion_destino  ON dbo.atraccion    (des_id)                  WHERE at_estado = 'A';
-- CREATE INDEX ix_atraccion_nombre   ON dbo.atraccion    (at_nombre)               WHERE at_estado = 'A';

-- TICKET
-- CREATE INDEX ix_ticket_atraccion   ON dbo.ticket       (at_id)                   WHERE tck_estado = 'A';

-- HORARIO
-- CREATE INDEX ix_horario_fecha      ON dbo.horario      (tck_id, hor_fecha)       WHERE hor_estado = 'A';

-- RESERVAS
-- CREATE INDEX ix_reservas_cliente   ON dbo.reservas     (cli_id)                  WHERE rev_estado <> 'C';
-- CREATE INDEX ix_reservas_horario   ON dbo.reservas     (hor_id)                  WHERE rev_estado <> 'C';
-- CREATE INDEX ix_reservas_fecha     ON dbo.reservas     (rev_fecha_reserva_utc);

-- RESERVA_DETALLE
-- CREATE INDEX ix_rdet_reserva       ON dbo.reserva_detalle (rev_id)               WHERE rdet_estado = 'A';
-- CREATE INDEX ix_rdet_ticket        ON dbo.reserva_detalle (tck_id)               WHERE rdet_estado = 'A';

-- RESENIA
-- CREATE INDEX ix_resenia_atraccion  ON dbo.resenia      (at_id)                   WHERE rsn_estado = 'A';

-- FACTURAS
-- CREATE INDEX ix_facturas_fecha     ON dbo.facturas     (fac_fecha_emision);

-- AUDITORIA_LOG
-- CREATE INDEX ix_auditlog_tabla_reg ON dbo.auditoria_log (log_tabla, log_registro_id);
-- CREATE INDEX ix_auditlog_fecha     ON dbo.auditoria_log (log_fecha_utc);
-- CREATE INDEX ix_auditlog_usuario   ON dbo.auditoria_log (log_usuario);

-- ============================================================
--  FIN DEL SCRIPT
--  Tablas creadas: 22
--  Cambio v2 → v3: RESERVA_DETALLE añadida.
-- ============================================================
