CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE datos_facturacion (
    dfac_id integer GENERATED BY DEFAULT AS IDENTITY,
    dfac_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    cli_guid uuid NOT NULL,
    dfac_tipo_identificacion character varying(20) NOT NULL,
    dfac_numero_identificacion character varying(30) NOT NULL,
    dfac_razon_social character varying(200),
    dfac_nombre character varying(100) NOT NULL,
    dfac_apellido character varying(100),
    dfac_correo character varying(150) NOT NULL,
    dfac_telefono character varying(20),
    dfac_direccion character varying(300),
    dfac_fecha_ingreso timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    dfac_usuario_ingreso character varying(100) NOT NULL,
    dfac_ip_ingreso character varying(45) NOT NULL,
    dfac_fecha_mod timestamp with time zone,
    dfac_usuario_mod character varying(100),
    dfac_ip_mod character varying(45),
    dfac_fecha_eliminacion timestamp with time zone,
    dfac_usuario_eliminacion character varying(100),
    dfac_ip_eliminacion character varying(45),
    dfac_estado character(1) NOT NULL DEFAULT 'A',
    dfac_row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_datos_facturacion" PRIMARY KEY (dfac_id),
    CONSTRAINT ck_datos_facturacion_estado CHECK (dfac_estado IN ('A','I')),
    CONSTRAINT ck_datos_facturacion_tipo_id CHECK (dfac_tipo_identificacion IN ('CC','RUC','PASAPORTE','CEDULA','OTRO'))
);

CREATE TABLE pagos (
    pag_id integer GENERATED BY DEFAULT AS IDENTITY,
    pag_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    rev_guid uuid NOT NULL,
    cli_guid uuid NOT NULL,
    dfac_id integer,
    pag_monto numeric(12,2) NOT NULL,
    pag_moneda character varying(3) NOT NULL DEFAULT 'USD',
    pag_metodo character varying(50) NOT NULL,
    pag_referencia character varying(100) NOT NULL,
    pag_fecha_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    pag_origen_canal character varying(50),
    pag_estado character varying(20) NOT NULL DEFAULT 'APROBADO',
    pag_usuario_ingreso character varying(100) NOT NULL,
    pag_ip_ingreso character varying(45) NOT NULL,
    pag_observacion character varying(500),
    pag_row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_pagos" PRIMARY KEY (pag_id),
    CONSTRAINT ck_pagos_estado CHECK (pag_estado IN ('PENDIENTE','APROBADO','RECHAZADO')),
    CONSTRAINT ck_pagos_monto CHECK (pag_monto >= 0),
    CONSTRAINT "FK_pagos_datos_facturacion_dfac_id" FOREIGN KEY (dfac_id) REFERENCES datos_facturacion (dfac_id) ON DELETE RESTRICT
);

CREATE TABLE facturas (
    fac_id integer GENERATED BY DEFAULT AS IDENTITY,
    fac_guid uuid NOT NULL DEFAULT (gen_random_uuid()),
    fac_numero character varying(50) NOT NULL,
    rev_guid uuid NOT NULL,
    cli_guid uuid NOT NULL,
    pag_id integer NOT NULL,
    dfac_id integer,
    fac_fecha_emision_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    fac_subtotal numeric(12,2) NOT NULL,
    fac_valor_iva numeric(12,2) NOT NULL,
    fac_total numeric(12,2) NOT NULL,
    fac_moneda character varying(3) NOT NULL DEFAULT 'USD',
    fac_observacion character varying(500),
    fac_usuario_ingreso character varying(100) NOT NULL,
    fac_ip_ingreso character varying(45) NOT NULL,
    fac_fecha_eliminacion timestamp with time zone,
    fac_usuario_eliminacion character varying(100),
    fac_ip_eliminacion character varying(45),
    fac_estado character(1) NOT NULL DEFAULT 'A',
    fac_row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_facturas" PRIMARY KEY (fac_id),
    CONSTRAINT ck_facturas_estado CHECK (fac_estado IN ('A','I')),
    CONSTRAINT ck_facturas_iva CHECK (fac_valor_iva >= 0),
    CONSTRAINT ck_facturas_subtotal CHECK (fac_subtotal >= 0),
    CONSTRAINT ck_facturas_total CHECK (fac_total >= 0),
    CONSTRAINT "FK_facturas_datos_facturacion_dfac_id" FOREIGN KEY (dfac_id) REFERENCES datos_facturacion (dfac_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_facturas_pagos_pag_id" FOREIGN KEY (pag_id) REFERENCES pagos (pag_id) ON DELETE RESTRICT
);

CREATE INDEX "IX_datos_facturacion_cli_guid" ON datos_facturacion (cli_guid);

CREATE UNIQUE INDEX "IX_datos_facturacion_dfac_guid" ON datos_facturacion (dfac_guid);

CREATE INDEX "IX_facturas_cli_guid" ON facturas (cli_guid);

CREATE INDEX "IX_facturas_dfac_id" ON facturas (dfac_id);

CREATE UNIQUE INDEX "IX_facturas_fac_guid" ON facturas (fac_guid);

CREATE UNIQUE INDEX "IX_facturas_fac_numero" ON facturas (fac_numero);

CREATE UNIQUE INDEX "IX_facturas_pag_id" ON facturas (pag_id);

CREATE UNIQUE INDEX "IX_facturas_rev_guid" ON facturas (rev_guid);

CREATE INDEX "IX_pagos_cli_guid" ON pagos (cli_guid);

CREATE INDEX "IX_pagos_dfac_id" ON pagos (dfac_id);

CREATE UNIQUE INDEX "IX_pagos_pag_guid" ON pagos (pag_guid);

CREATE UNIQUE INDEX "IX_pagos_pag_referencia" ON pagos (pag_referencia);

CREATE INDEX "IX_pagos_rev_guid" ON pagos (rev_guid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515004901_InitialFacturacionSchema', '10.0.4');

COMMIT;

