// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelDreams.MsAtracciones.DataAccess.Context;

#nullable disable

namespace TravelDreams.MsAtracciones.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    partial class AtraccionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", b =>
                {
                    b.Property<int>("at_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("at_id"));

                    b.Property<string>("at_descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("at_direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("at_disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("at_duracion_minutos")
                        .HasColumnType("integer");

                    b.Property<string>("at_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("at_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("at_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("at_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("at_free_cancellation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("at_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("at_incluye_acompaniante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("at_incluye_transporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("at_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("at_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("at_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("at_nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("at_num_establecimiento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("at_precio_referencia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("at_punto_encuentro")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("at_skip_the_line")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("at_total_resenias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("at_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("at_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("at_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("des_id")
                        .HasColumnType("integer");

                    b.HasKey("at_id");

                    b.HasIndex("at_guid")
                        .IsUnique();

                    b.HasIndex("at_nombre");

                    b.HasIndex("des_id");

                    b.ToTable("atraccion", null, t =>
                        {
                            t.HasCheckConstraint("ck_atraccion_duracion", "at_duracion_minutos IS NULL OR at_duracion_minutos > 0");

                            t.HasCheckConstraint("ck_atraccion_estado", "at_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_atraccion_precio", "at_precio_referencia IS NULL OR at_precio_referencia >= 0");

                            t.HasCheckConstraint("ck_atraccion_resenias", "at_total_resenias >= 0");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.CategoriaEntity", b =>
                {
                    b.Property<int>("cat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cat_id"));

                    b.Property<string>("cat_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("cat_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("cat_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("cat_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("cat_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("cat_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cat_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cat_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cat_nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("cat_parent_id")
                        .HasColumnType("integer");

                    b.Property<string>("cat_tagname")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("cat_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cat_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("cat_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("cat_id");

                    b.HasIndex("cat_guid")
                        .IsUnique();

                    b.HasIndex("cat_parent_id");

                    b.HasIndex("cat_tagname");

                    b.ToTable("categoria", null, t =>
                        {
                            t.HasCheckConstraint("ck_categoria_estado", "cat_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_categoria_selfref", "cat_parent_id IS NULL OR cat_parent_id <> cat_id");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.DestinoEntity", b =>
                {
                    b.Property<int>("des_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("des_id"));

                    b.Property<string>("des_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("des_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("des_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("des_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("des_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("des_imagen_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("des_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("des_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("des_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("des_nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("des_pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("des_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("des_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("des_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("des_id");

                    b.HasIndex("des_guid")
                        .IsUnique();

                    b.HasIndex("des_pais");

                    b.ToTable("destino", null, t =>
                        {
                            t.HasCheckConstraint("ck_destino_estado", "des_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.IdiomaEntity", b =>
                {
                    b.Property<int>("id_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_id"));

                    b.Property<string>("id_codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("id_descripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("id_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("id_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("id_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("id_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("id_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("id_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("id_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("id_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("id_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("id_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("id_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_id");

                    b.HasIndex("id_codigo")
                        .IsUnique();

                    b.HasIndex("id_descripcion")
                        .IsUnique();

                    b.HasIndex("id_guid")
                        .IsUnique();

                    b.ToTable("idioma", null, t =>
                        {
                            t.HasCheckConstraint("ck_idioma_estado", "id_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.ImagenEntity", b =>
                {
                    b.Property<int>("img_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("img_id"));

                    b.Property<string>("img_descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("img_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("img_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("img_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("img_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("img_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("img_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("img_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("img_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("img_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("img_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("img_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("img_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("img_id");

                    b.HasIndex("img_guid")
                        .IsUnique();

                    b.ToTable("imagen", null, t =>
                        {
                            t.HasCheckConstraint("ck_imagen_estado", "img_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.IncluyeEntity", b =>
                {
                    b.Property<int>("inc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("inc_id"));

                    b.Property<string>("inc_descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("inc_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<Guid>("inc_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("inc_tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("INCLUYE");

                    b.HasKey("inc_id");

                    b.HasIndex("inc_guid")
                        .IsUnique();

                    b.ToTable("incluye", null, t =>
                        {
                            t.HasCheckConstraint("ck_incluye_estado", "inc_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_incluye_tipo", "inc_tipo IN ('INCLUYE','NO_INCLUYE','ETIQUETA')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.AtraccionIncluyeEntity", b =>
                {
                    b.Property<int>("inc_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<string>("ai_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ai_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ai_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ai_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ai_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("inc_id", "at_id");

                    b.HasIndex("at_id");

                    b.ToTable("atraccion_incluye", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.CategoriaAtraccionEntity", b =>
                {
                    b.Property<int>("cat_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<string>("ca_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ca_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ca_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ca_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ca_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("cat_id", "at_id");

                    b.HasIndex("at_id");

                    b.ToTable("categoria_atraccion", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.IdiomaAtraccionEntity", b =>
                {
                    b.Property<int>("id_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<string>("ia_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ia_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ia_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ia_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ia_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_id", "at_id");

                    b.HasIndex("at_id");

                    b.ToTable("idioma_atraccion", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.ImagenAtraccionEntity", b =>
                {
                    b.Property<int>("img_id")
                        .HasColumnType("integer");

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<bool>("ima_es_principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ima_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("ima_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ima_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ima_orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ima_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ima_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("img_id", "at_id");

                    b.HasIndex("at_id", "ima_es_principal");

                    b.ToTable("imagen_atraccion", (string)null);
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Operacion.HorarioEntity", b =>
                {
                    b.Property<int>("hor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("hor_id"));

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<int>("hor_cupos_disponibles")
                        .HasColumnType("integer");

                    b.Property<string>("hor_dias_semana")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("0,1,2,3,4,5,6");

                    b.Property<string>("hor_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateOnly>("hor_fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("hor_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("hor_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("hor_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("hor_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeOnly?>("hor_hora_fin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("hor_hora_inicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("hor_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("hor_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("hor_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("hor_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("hor_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("hor_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("hor_id");

                    b.HasIndex("hor_guid")
                        .IsUnique();

                    b.HasIndex("at_id", "hor_fecha", "hor_hora_inicio")
                        .IsUnique();

                    b.ToTable("horario", null, t =>
                        {
                            t.HasCheckConstraint("ck_horario_cupos", "hor_cupos_disponibles >= 0");

                            t.HasCheckConstraint("ck_horario_estado", "hor_estado IN ('A','I')");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Operacion.ReseniaEntity", b =>
                {
                    b.Property<int>("rsn_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rsn_id"));

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("rev_guid")
                        .HasColumnType("uuid");

                    b.Property<string>("rsn_comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("rsn_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime>("rsn_fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("rsn_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("rsn_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("rsn_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("rsn_ip_creacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rsn_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("rsn_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<short>("rsn_rating")
                        .HasColumnType("smallint");

                    b.Property<string>("rsn_usuario_creacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rsn_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("rsn_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("rsn_id");

                    b.HasIndex("at_id");

                    b.HasIndex("rev_guid")
                        .IsUnique();

                    b.HasIndex("rsn_guid")
                        .IsUnique();

                    b.ToTable("resenia", null, t =>
                        {
                            t.HasCheckConstraint("ck_resenia_estado", "rsn_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_resenia_rating", "rsn_rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Operacion.TicketEntity", b =>
                {
                    b.Property<int>("tck_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tck_id"));

                    b.Property<int>("at_id")
                        .HasColumnType("integer");

                    b.Property<int>("tck_capacidad_maxima")
                        .HasColumnType("integer");

                    b.Property<string>("tck_estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasDefaultValue("A")
                        .IsFixedLength();

                    b.Property<DateTime?>("tck_fecha_eliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("tck_fecha_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("tck_fecha_mod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("tck_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("tck_ip_eliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tck_ip_ingreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tck_ip_mod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tck_moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<decimal>("tck_precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("tck_tipo_participante")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Adulto");

                    b.Property<string>("tck_titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("tck_usuario_eliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tck_usuario_ingreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tck_usuario_mod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("tck_id");

                    b.HasIndex("at_id");

                    b.HasIndex("tck_guid")
                        .IsUnique();

                    b.ToTable("ticket", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_capacidad", "tck_capacidad_maxima > 0");

                            t.HasCheckConstraint("ck_ticket_estado", "tck_estado IN ('A','I')");

                            t.HasCheckConstraint("ck_ticket_precio", "tck_precio >= 0");
                        });
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.DestinoEntity", "Destino")
                        .WithMany("Atracciones")
                        .HasForeignKey("des_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.CategoriaEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.CategoriaEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("cat_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.AtraccionIncluyeEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("AtraccionIncluyes")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.IncluyeEntity", "Incluye")
                        .WithMany("AtraccionIncluyes")
                        .HasForeignKey("inc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Incluye");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.CategoriaAtraccionEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.CategoriaEntity", "Categoria")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.IdiomaAtraccionEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.IdiomaEntity", "Idioma")
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("id_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.CatalogoRelaciones.ImagenAtraccionEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("ImagenAtracciones")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.ImagenEntity", "Imagen")
                        .WithMany("ImagenAtracciones")
                        .HasForeignKey("img_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Operacion.HorarioEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("Horarios")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Operacion.ReseniaEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("Resenias")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Operacion.TicketEntity", b =>
                {
                    b.HasOne("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", "Atraccion")
                        .WithMany("Tickets")
                        .HasForeignKey("at_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.AtraccionEntity", b =>
                {
                    b.Navigation("AtraccionIncluyes");

                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Horarios");

                    b.Navigation("IdiomaAtracciones");

                    b.Navigation("ImagenAtracciones");

                    b.Navigation("Resenias");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.CategoriaEntity", b =>
                {
                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.DestinoEntity", b =>
                {
                    b.Navigation("Atracciones");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.IdiomaEntity", b =>
                {
                    b.Navigation("IdiomaAtracciones");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.ImagenEntity", b =>
                {
                    b.Navigation("ImagenAtracciones");
                });

            modelBuilder.Entity("TravelDreams.MsAtracciones.DataAccess.Entities.Catalogo.IncluyeEntity", b =>
                {
                    b.Navigation("AtraccionIncluyes");
                });
#pragma warning restore 612, 618
        }
    }
}
